### OPW Episode Cohort Analysis

Builds its own 6 month Orange / Purple / WhatsApp cohort from Athena.
Does not use FinalData.xlsx.

Output: `OPW_Episode_Cohort_Analysis.xlsx` (16 sheets). Cells after the export step print the same tables in the notebook.

In [18]:
import json
import os
import time
from datetime import datetime
from pathlib import Path

import awswrangler as wr
import boto3
import numpy as np
import pandas as pd
from dotenv import load_dotenv

ANALYSIS_MONTHS = 6
ANALYSIS_END = pd.Timestamp.now().normalize() + pd.Timedelta(hours=23, minutes=59, seconds=59)
WINDOW_START = ANALYSIS_END - pd.DateOffset(months=ANALYSIS_MONTHS)
WINDOW_START_STR = WINDOW_START.strftime("%Y-%m-%d %H:%M:%S")

load_dotenv(Path.cwd() / ".env")


def _env(name, default=""):
    return (os.getenv(name) or default).strip()


AWS_REGION = _env("AWS_REGION", "ap-south-1")
ATHENA_DB = _env("ATHENA_DATABASE", "leadsdb-prod")
ATHENA_WORKGROUP = _env("ATHENA_WORKGROUP", "asbl_analytics_prod")
S3_OUTPUT = _env("ATHENA_OUTPUT_LOCATION", "s3://airflow-etl-db/athena_storage/")
AWS_ACCESS_KEY_ID = _env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = _env("AWS_SECRET_ACCESS_KEY")

# ponytail: this laptop has no ASBL profile; .env keys are the working auth path
session_kwargs = {"region_name": AWS_REGION}
if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    session_kwargs.update(
        aws_access_key_id=AWS_ACCESS_KEY_ID,
        aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    )
elif "ASBL" in boto3.Session().available_profiles:
    session_kwargs["profile_name"] = "ASBL"

session = boto3.Session(**session_kwargs)


def athena_read(sql):
    return wr.athena.read_sql_query(
        sql=sql,
        database=ATHENA_DB,
        boto3_session=session,
        workgroup=ATHENA_WORKGROUP,
        s3_output=S3_OUTPUT,
        ctas_approach=False,
    )


def athena_batches(sql_template, ids, batch_size=500):
    clean = list(
        {
            str(x).replace(".0", "").strip()
            for x in ids
            if pd.notna(x) and str(x).strip() not in ("", "nan", "None")
        }
    )
    parts = [athena_read(sql_template.format(ids=", ".join(f"'{b}'" for b in clean[i : i + batch_size])))
             for i in range(0, len(clean), batch_size)]
    return pd.concat(parts, ignore_index=True) if parts else pd.DataFrame()


_leadSourceDF = athena_read(f'SELECT _id, name FROM "{ATHENA_DB}"."leadsources"')
_projectDF = athena_read(f'SELECT _id, name FROM "{ATHENA_DB}"."projects"')


def id_name_map(lookup_df):
    return dict(zip(
        lookup_df["_id"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip(),
        lookup_df["name"].astype(str).str.strip(),
    ))


SOURCE_NAME_MAP = id_name_map(_leadSourceDF)
PROJECT_NAME_MAP = id_name_map(_projectDF)


def map_id_col(df, col, lookup):
    if col not in df.columns:
        return df
    ids = df[col].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
    blank = df[col].isna() | ids.isin(["", "nan", "None", "<NA>", "NaT"])
    mapped = ids.map(lookup)
    df[col] = mapped.where(mapped.notna() & ~blank, ids.where(~blank, pd.NA))
    return df


def replace_ids_with_names(df):
    df = map_id_col(df, "project", PROJECT_NAME_MAP)
    df = map_id_col(df, "bornSource", SOURCE_NAME_MAP)
    df = map_id_col(df, "source", SOURCE_NAME_MAP)
    df = map_id_col(df, "episode_source", SOURCE_NAME_MAP)
    df.drop(
        columns=["episode_source_id", "episode_source_name", "project_name", "bornSource_name", "source_name"],
        errors="ignore",
        inplace=True,
    )
    return df


print(f"Athena: db={ATHENA_DB} workgroup={ATHENA_WORKGROUP}")
print(f"Analysis window: {WINDOW_START.date()} to {ANALYSIS_END.date()}")
print(f"Lead sources loaded: {len(_leadSourceDF):,}")
print(f"Projects loaded: {len(_projectDF):,}")

Athena: db=leadsdb-prod workgroup=asbl_analytics_prod
Analysis window: 2026-02-19 to 2026-08-19
Lead sources loaded: 315
Projects loaded: 12

In [19]:
import json
from datetime import datetime
from pathlib import Path

import awswrangler as wr
import boto3
import numpy as np
import pandas as pd
from scipy import stats

EPISODE_ORDER = ["Episode 1", "Episode 2", "Episode 3", "Episode 4", "Episode 5+"]
META_EXCLUDE = {
    "lead", "lead_clean", "leadId", "lead_oid", "masterLeadId", "globalId", "visitorId",
    "project", "status", "episode_id", "episode_number", "episode_group",
    "episode_start_time", "episode_end_time", "lead_createdAt", "start_stage", "end_stage",
    "stage_before_ni", "stage_transition_path", "cancellation_reason_at_episode_end",
    "bornSource", "source", "secondarySource", "episode_source",
    "original_source", "qualifying_source", "reactivation_source", "resubmission_source",
    "qualifying_event_types", "qualifying_channels", "is_orange_lead", "is_purple_lead",
    "is_whatsapp_lead", "first_qualifying_event_time", "last_qualifying_event_time",
    "qualifying_event_count", "prev_episode_number", "lead_curr", "lead_prev", "transition_pair",
}

def _pick_col(df, *candidates):
    lower = {c.lower(): c for c in df.columns}
    for name in candidates:
        if name in df.columns:
            return name
        if name.lower() in lower:
            return lower[name.lower()]
    return None

def _to_bool(series):
    return series.astype(str).str.strip().str.lower().isin(["1", "true", "t", "yes"])

def _parse_secondary_events(val):
    if not isinstance(val, str) or not val.strip() or val.strip() == "[]":
        return []
    try:
        parsed = json.loads(val)
    except Exception:
        return []
    return [x for x in parsed if isinstance(x, dict)] if isinstance(parsed, list) else []

def _classify_event_type(event_time, lead_created, episodes):
    if pd.isna(event_time):
        return "unknown"
    if pd.notna(lead_created) and abs((event_time - lead_created).total_seconds()) <= 86400:
        return "born"
    if episodes is not None and not episodes.empty:
        ep_starts = pd.to_datetime(episodes["episode_start_time"], errors="coerce")
        if ((ep_starts - event_time).abs() <= pd.Timedelta(days=1)).any():
            ep_match = episodes.loc[(ep_starts - event_time).abs() <= pd.Timedelta(days=1)]
            if (ep_match["episode_number"] > 1).any():
                return "reactivated"
    return "resubmitted"

def resolve_lead_flag_columns(leads_df):
    return {
        "is_orange": _pick_col(leads_df, "is_orange", "isorange", "isOrange"),
        "is_purple": _pick_col(leads_df, "is_purple", "ispurple", "ispurplelead", "isPurple"),
        "orange_time": _pick_col(leads_df, "orange_lead_time", "orangeleadtime", "orangeLeadTime", "is_orange_time"),
        "purple_time": _pick_col(leads_df, "purple_lead_time", "purpleleadtime", "purpleLeadTime", "is_purple_time"),
        "born_source": _pick_col(leads_df, "bornSource", "bornsource"),
        "secondary_source": _pick_col(leads_df, "secondarySource", "secondarysource"),
        "lead_created": _pick_col(leads_df, "lead_createdAt", "createdat", "createdAt"),
        "lead_id": _pick_col(leads_df, "lead", "_id"),
    }

def build_whatsapp_source_ids(source_df):
    name_col = _pick_col(source_df, "name")
    id_col = _pick_col(source_df, "_id")
    if not name_col or not id_col:
        return set()
    mask = source_df[name_col].astype(str).str.contains("whatsapp", case=False, na=False)
    return set(source_df.loc[mask, id_col].astype(str).str.strip())

def extract_lead_qualifying_events(lead_row, cols, wa_source_ids, source_name_map, window_start, window_end, episodes=None):
    """Return qualifying events for one lead.

    Cohort logic is OR across channels:
      - Orange timestamp in window
      - Purple timestamp in window
      - WhatsApp born / reactivated / resubmitted in window

    Orange and Purple do NOT require a specific bornSource.
    WhatsApp reactivation/resubmission also does NOT require WhatsApp birth.
    """
    events = []
    lead_created = pd.to_datetime(lead_row.get(cols["lead_created"]), errors="coerce") if cols["lead_created"] else pd.NaT

    def add_event(channel, event_time, event_type=None):
        if pd.isna(event_time) or event_time < window_start or event_time > window_end:
            return
        events.append({
            "channel": channel,
            "event_time": event_time,
            "event_type": event_type or _classify_event_type(event_time, lead_created, episodes),
        })

    # --- Orange (any original birth source) ---
    if cols["orange_time"]:
        orange_ts = pd.to_datetime(lead_row.get(cols["orange_time"]), errors="coerce")
        if pd.notna(orange_ts):
            add_event("Orange", orange_ts)

    # --- Purple (any original birth source) ---
    if cols["purple_time"]:
        purple_ts = pd.to_datetime(lead_row.get(cols["purple_time"]), errors="coerce")
        if pd.notna(purple_ts):
            add_event("Purple", purple_ts)

    # --- WhatsApp born ---
    born_source = str(lead_row.get(cols["born_source"], "")).strip() if cols["born_source"] else ""
    born_source_name = source_name_map.get(born_source, born_source).lower()
    if born_source in wa_source_ids or "whatsapp" in born_source_name:
        add_event("WhatsApp", lead_created, "born")

    # --- WhatsApp / Orange / Purple reactivation or resubmission from secondarySource ---
    for item in _parse_secondary_events(lead_row.get(cols["secondary_source"]) if cols["secondary_source"] else None):
        event_time = pd.to_datetime(item.get("date"), errors="coerce")
        if pd.isna(event_time) or event_time < window_start or event_time > window_end:
            continue

        src = str(item.get("source", "")).strip()
        src_name = source_name_map.get(src, src).lower()
        is_react = item.get("isReactivation")
        is_reactivation = is_react is True or str(is_react).lower() == "true"
        event_type = "reactivated" if is_reactivation else "resubmitted"

        # WhatsApp reactivation/resubmission (born by any source)
        if src in wa_source_ids or "whatsapp" in src_name:
            add_event("WhatsApp", event_time, event_type)

        # Orange/Purple event aligned to this secondarySource event timestamp
        if cols["orange_time"]:
            orange_ts = pd.to_datetime(lead_row.get(cols["orange_time"]), errors="coerce")
            if pd.notna(orange_ts) and abs((orange_ts - event_time).total_seconds()) <= 86400:
                add_event("Orange", event_time, event_type)
        if cols["purple_time"]:
            purple_ts = pd.to_datetime(lead_row.get(cols["purple_time"]), errors="coerce")
            if pd.notna(purple_ts) and abs((purple_ts - event_time).total_seconds()) <= 86400:
                add_event("Purple", event_time, event_type)

    return events

def build_cohort_lead_summary(leads_df, source_df, episodes_df, analysis_end=None, months=6):
    analysis_end = pd.Timestamp(analysis_end or datetime.now()).normalize() + pd.Timedelta(hours=23, minutes=59, seconds=59)
    window_start = analysis_end - pd.DateOffset(months=months)
    cols = resolve_lead_flag_columns(leads_df)
    wa_source_ids = build_whatsapp_source_ids(source_df)
    source_name_map = {}
    name_col = _pick_col(source_df, "name")
    id_col = _pick_col(source_df, "_id")
    if name_col and id_col:
        source_name_map = dict(zip(source_df[id_col].astype(str).str.strip(), source_df[name_col].astype(str)))

    lead_col = cols["lead_id"] or "lead"
    leads = leads_df.copy()
    leads["lead_clean"] = leads[lead_col].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
    ep = episodes_df.copy()
    ep["lead_clean"] = ep["lead"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()

    episode_leads = set(ep["lead_clean"].unique())
    rows = []
    for lead_clean, lead_grp in leads.groupby("lead_clean"):
        if lead_clean not in episode_leads:
            continue
        lead_row = lead_grp.iloc[0]
        lead_eps = ep[ep["lead_clean"] == lead_clean].sort_values("episode_number")
        # OR logic: any qualifying Orange / Purple / WhatsApp event in window is enough
        events = extract_lead_qualifying_events(lead_row, cols, wa_source_ids, source_name_map, window_start, analysis_end, lead_eps)
        if not events:
            continue
        ev_df = pd.DataFrame(events)
        channels = sorted(ev_df["channel"].unique().tolist())
        born_channels = sorted(ev_df.loc[ev_df["event_type"] == "born", "channel"].unique().tolist())
        react_channels = sorted(ev_df.loc[ev_df["event_type"] == "reactivated", "channel"].unique().tolist())
        resub_channels = sorted(ev_df.loc[ev_df["event_type"] == "resubmitted", "channel"].unique().tolist())
        rows.append({
            "lead": lead_clean,
            "qualifying_channels": "|".join(channels),
            "qualifying_event_types": "|".join(sorted(ev_df["event_type"].unique().tolist())),
            "original_source": born_channels[0] if born_channels else channels[0],
            "qualifying_source": "|".join(channels),
            "reactivation_source": "|".join(react_channels) if react_channels else "",
            "resubmission_source": "|".join(resub_channels) if resub_channels else "",
            "is_orange_lead": int("Orange" in channels),
            "is_purple_lead": int("Purple" in channels),
            "is_whatsapp_lead": int("WhatsApp" in channels),
            "qualifying_event_count": len(events),
            "first_qualifying_event_time": ev_df["event_time"].min(),
            "last_qualifying_event_time": ev_df["event_time"].max(),
        })
    return pd.DataFrame(rows) if rows else pd.DataFrame(columns=[
        "lead", "qualifying_channels", "qualifying_event_types", "original_source",
        "qualifying_source", "reactivation_source", "resubmission_source",
        "is_orange_lead", "is_purple_lead", "is_whatsapp_lead",
        "qualifying_event_count", "first_qualifying_event_time", "last_qualifying_event_time",
    ])

def enrich_episode_dataset(df_master, cohort_summary):
    df = df_master.copy()
    df["lead_clean"] = df["lead"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
    df = df.merge(cohort_summary.rename(columns={"lead": "lead_clean"}), on="lead_clean", how="inner")
    df["episode_group"] = np.where(df["episode_number"] >= 5, "Episode 5+", "Episode " + df["episode_number"].astype(int).astype(str))
    if "total_attempted_calls" in df.columns and "total_answered_calls" in df.columns and "pickup_ratio" not in df.columns:
        df["pickup_ratio"] = np.where(df["total_attempted_calls"] > 0, df["total_answered_calls"] / df["total_attempted_calls"], 0.0)
    if {"total_web_timespent", "active_session_count"}.issubset(df.columns) and "avg_web_activity" not in df.columns:
        df["avg_web_activity"] = np.where(df["active_session_count"] > 0, df["total_web_timespent"] / df["active_session_count"], 0.0)
    df["stage_transition_path"] = (
        df["start_stage"].astype(str).str.strip() if "start_stage" in df.columns else ""
    ) + " -> " + (
        df["stage_before_ni"].astype(str).str.strip() if "stage_before_ni" in df.columns else ""
    )
    return df.drop(columns=["lead_clean"], errors="ignore")

print("OPW cohort helper functions loaded.")

OPW cohort helper functions loaded.

In [20]:
# Step 1: candidate leads from Athena (6 month event window, OR logic at row level)
wa_ids = set(
    _leadSourceDF.loc[_leadSourceDF["name"].astype(str).str.contains("whatsapp", case=False, na=False), "_id"]
    .astype(str)
    .str.strip()
)
wa_sql = ", ".join(f"'{x}'" for x in wa_ids) if wa_ids else "''"

# Athena leads dump uses lowercase names. There is no isorange column.
# Orange/Purple come from timestamps (+ ispurplelead when present).
leads_desc = athena_read(
    f"""
    SELECT column_name
    FROM information_schema.columns
    WHERE table_schema = '{ATHENA_DB}'
      AND table_name = 'leads'
    """
)
lead_cols = {str(c).lower(): str(c) for c in leads_desc.iloc[:, 0]}


def _sql_col(*names):
    for n in names:
        if n.lower() in lead_cols:
            return lead_cols[n.lower()]
    return None


orange_time_col = _sql_col("orangeleadtime", "orange_lead_time", "orangeLeadTime")
purple_time_col = _sql_col("purpleleadtime", "purple_lead_time", "purpleLeadTime")
orange_flag_col = _sql_col("isorange", "is_orange", "isOrange")
purple_flag_col = _sql_col("ispurplelead", "is_purple", "ispurple", "isPurple")
born_col = _sql_col("bornsource", "bornSource")
sec_col = _sql_col("secondarysource", "secondarySource")
created_col = _sql_col("createdat", "createdAt")
updated_col = _sql_col("updatedat", "updatedAt")
gid_col = _sql_col("globalid", "globalId")
project_col = _sql_col("project")
status_col = _sql_col("status")
source_col = _sql_col("source")
leadid_col = _sql_col("leadid", "leadId")
masterleadid_col = _sql_col("masterleadid", "masterLeadId")

selects = ["_id"]
if born_col:
    selects.append(f"{born_col} AS bornSource")
if source_col:
    selects.append(f"{source_col} AS source")
if sec_col:
    selects.append(f"{sec_col} AS secondarySource")
if created_col:
    selects.append(f"{created_col} AS lead_createdAt")
if orange_flag_col:
    selects.append(f"{orange_flag_col} AS is_orange")
if purple_flag_col:
    selects.append(f"{purple_flag_col} AS is_purple")
if orange_time_col:
    selects.append(f"{orange_time_col} AS orange_lead_time")
if purple_time_col:
    selects.append(f"{purple_time_col} AS purple_lead_time")
if gid_col:
    selects.append(f"{gid_col} AS globalId")
if project_col:
    selects.append(f"{project_col} AS project")
if status_col:
    selects.append(f"{status_col} AS status")
if leadid_col:
    selects.append(f"{leadid_col} AS leadId")
if masterleadid_col:
    selects.append(f"{masterleadid_col} AS masterLeadId")

where_parts = []
if orange_time_col:
    where_parts.append(f"{orange_time_col} >= TIMESTAMP '{WINDOW_START_STR}'")
if purple_time_col:
    where_parts.append(f"{purple_time_col} >= TIMESTAMP '{WINDOW_START_STR}'")
if born_col and created_col:
    where_parts.append(f"({born_col} IN ({wa_sql}) AND {created_col} >= TIMESTAMP '{WINDOW_START_STR}')")
if updated_col:
    where_parts.append(f"{updated_col} >= TIMESTAMP '{WINDOW_START_STR}'")
if not where_parts:
    raise RuntimeError("Could not find orange/purple/whatsapp columns on leads")

candidate_sql = f"""
SELECT
    {", ".join(selects)}
FROM "{ATHENA_DB}"."leads"
WHERE {" OR ".join(where_parts)}
"""
leads_candidates = athena_read(candidate_sql)
print(f"Candidate leads from Athena: {len(leads_candidates):,}")
print("Lead columns used:", ", ".join(selects))

# Step 2: refine with Python OR rules (Orange / Purple / WhatsApp)
source_name_map = dict(zip(_leadSourceDF["_id"].astype(str).str.strip(), _leadSourceDF["name"].astype(str)))
wa_source_ids = wa_ids
cols = resolve_lead_flag_columns(leads_candidates)

qualifying_leads = []
for lead_clean, grp in leads_candidates.assign(
    lead_clean=leads_candidates["_id"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
).groupby("lead_clean"):
    events = extract_lead_qualifying_events(
        grp.iloc[0], cols, wa_source_ids, source_name_map, WINDOW_START, ANALYSIS_END, episodes=None
    )
    if events:
        qualifying_leads.append(lead_clean)

qualifying_leads = sorted(set(qualifying_leads))
print(f"Qualifying OPW leads (OR filter): {len(qualifying_leads):,}")

Candidate leads from Athena: 1,249,169
Lead columns used: _id, bornsource AS bornSource, source AS source, secondarysource AS secondarySource, createdat AS lead_createdAt, ispurplelead AS is_purple, orangeleadtime AS orange_lead_time, purpleleadtime AS purple_lead_time, globalid AS globalId, project AS project, status AS status, leadid AS leadId, masterleadid AS masterLeadId
Qualifying OPW leads (OR filter): 34,736

In [21]:
# Step 3: full stage history and episodes for qualifying leads only
_leadsStageDF = athena_batches(
    """
    SELECT _id, lead, stage, iscurrent AS isCurrent, createdat AS createdAt,
           reason, isstagemovement AS isStageMovement, cancelledreason AS cancellation_reason, comments
    FROM "{db}"."leadstagehistories"
    WHERE lead IN ({{ids}})
    """.format(db=ATHENA_DB),
    qualifying_leads,
)

df_hist = _leadsStageDF.copy()
df_hist["createdAt_dt"] = pd.to_datetime(df_hist["createdAt"], errors="coerce")
df_hist["lead_clean"] = df_hist["lead"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
df_hist = df_hist.dropna(subset=["lead_clean", "createdAt_dt"]).sort_values(["lead_clean", "createdAt_dt"]).reset_index(drop=True)
df_hist["prev_stage"] = df_hist.groupby("lead_clean")["stage"].shift(1)

is_duplicate_ni = (df_hist["stage"] == "Not Interested") & (df_hist["prev_stage"] == "Not Interested")
df_valid = df_hist[~is_duplicate_ni].copy().reset_index(drop=True)
df_valid["prev_stage"] = df_valid.groupby("lead_clean")["stage"].shift(1)
df_valid["is_first_ni"] = (df_valid["stage"] == "Not Interested") & (df_valid["prev_stage"] != "Not Interested")
df_valid["is_last_rec"] = df_valid["lead_clean"] != df_valid["lead_clean"].shift(-1)
df_valid["is_ep_end"] = df_valid["is_first_ni"] | df_valid["is_last_rec"]
df_valid["ep_end_shift"] = df_valid.groupby("lead_clean")["is_ep_end"].shift(1).fillna(False).astype(int)
df_valid["episode_number"] = df_valid.groupby("lead_clean")["ep_end_shift"].cumsum() + 1

df_episodes = df_valid.groupby(["lead_clean", "episode_number"]).agg(
    episode_start_time=("createdAt_dt", "min"),
    episode_end_time=("createdAt_dt", "max"),
    start_stage=("stage", "first"),
    end_stage=("stage", "last"),
    total_stage_movements=("createdAt_dt", "count"),
).reset_index().rename(columns={"lead_clean": "lead"})
df_episodes["episode_id"] = df_episodes["lead"] + "_" + df_episodes["episode_number"].astype(str)
max_ep = df_episodes.groupby("lead")["episode_number"].transform("max")
df_episodes["is_reactivated_episode"] = (df_episodes["episode_number"] < max_ep).astype(int)

leads_for_cohort = leads_candidates[
    leads_candidates["_id"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip().isin(qualifying_leads)
].copy()
df_episodes["lead_clean"] = df_episodes["lead"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
leads_for_cohort["lead_clean"] = leads_for_cohort["_id"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
df5 = df_episodes.merge(leads_for_cohort, on="lead_clean", how="left", suffixes=("", "_lead"))
df5.drop(columns=["lead_clean"], errors="ignore", inplace=True)
print(f"Episode rows (all episodes for qualifying leads): {len(df5):,}")

Episode rows (all episodes for qualifying leads): 45,115

In [22]:
# Step 4: web, stage, whatsapp, call features (no 3 month lead-created filter)
# globalId -> visitorId
if "globalId" in df5.columns:
    gids = df5["globalId"].dropna().astype(str).str.strip().unique().tolist()
    df3 = athena_batches(
        f'SELECT globalid AS globalId, visitorid AS visitorId, project FROM "{ATHENA_DB}"."globalvisitorlogs" WHERE globalid IN ({{ids}})',
        gids,
    )
    if not df3.empty and {"project", "globalId", "visitorId"}.issubset(df3.columns):
        df5 = df5.merge(df3, on=["project", "globalId"], how="left")
    elif "visitorId" not in df5.columns:
        df5["visitorId"] = np.nan
else:
    df5["visitorId"] = np.nan

# visitor logs for all qualifying visitor IDs (episode windows applied later)
visitor_ids = df5["visitorId"].dropna().astype(str).str.replace(r"\.0$", "", regex=True).str.strip().unique().tolist()
df6_parts = []
for i in range(0, len(visitor_ids), 500):
    batch = visitor_ids[i : i + 500]
    ids = ", ".join(f"'{v}'" for v in batch)
    q = f"""
        SELECT _id, visitorid AS visitorId, globalid AS globalId,
               cummulativetimespent AS cummulativeTimeSpent, createdat AS createdAt,
               instancenumber AS instanceNumber, pages, pricesheetsopened AS priceSheetsOpened,
               whatsappclicked AS whatsappClicked
        FROM "{ATHENA_DB}"."visitorlogs"
        WHERE visitorid IN ({ids})
    """
    df6_parts.append(athena_read(q))
df6 = pd.concat(df6_parts, ignore_index=True) if df6_parts else pd.DataFrame()

# track events
if not df6.empty:
    botlogs = df6["_id"].dropna().astype(str).str.replace(r"\.0$", "", regex=True).str.strip().unique().tolist()
    df7 = athena_batches(f'SELECT botlog AS botLog, trackevents AS trackEvents FROM "{ATHENA_DB}"."userredirecttracks" WHERE botlog IN ({{ids}})', botlogs)
    df6 = df6.merge(df7, left_on="_id", right_on="botLog", how="left")
else:
    df7 = pd.DataFrame()

# parse pages + click flags (same rules as leadstagehistories)
def parse_pages_json(val):
    d = {f"{p}_timespent": 0.0 for p in ["home","price","plan","location","amenities","media","specifications"]}
    if isinstance(val, str) and val.strip():
        try:
            p = json.loads(val)
            if isinstance(p, dict):
                for k, v in p.items():
                    key = f"{k.lower().strip()}_timespent"
                    if key in d:
                        d[key] = float(v) if pd.notnull(v) else 0.0
        except Exception:
            pass
    return d

def parse_track_events_json(val):
    flags = {k: 0 for k in ["is_site_visit_book_clicked","is_whatsapp_clicked","is_brochure_downloaded","is_price_sheet_viewed","is_cost_sheet_clicked"]}
    if isinstance(val, str) and val.strip():
        try:
            val = json.loads(val)
        except Exception:
            val = []
    if not isinstance(val, list):
        return flags
    for item in val:
        if not isinstance(item, dict):
            continue
        evs = item.get("eventName")
        if isinstance(evs, str):
            evs = [evs]
        for ev in evs or []:
            u = str(ev).upper()
            if any(k in u for k in ["BOOK_A_SITE_VISIT","SITE_VISIT_BTN","START_SITE_VISIT"]):
                flags["is_site_visit_book_clicked"] = 1
            if any(k in u for k in ["WHATSAPP","WA_"]):
                flags["is_whatsapp_clicked"] = 1
            if any(k in u for k in ["BROCHURE","DOWNLOAD","PDF"]):
                flags["is_brochure_downloaded"] = 1
            if any(k in u for k in ["PRICE_SHEET","PRICE_SECTION","PRICESHEET","PRICE_PARTICULARS","UNLOCK_PRICE"]):
                flags["is_price_sheet_viewed"] = 1
            if any(k in u for k in ["COST_SHEET","SHOW_COST_SHEET","VIEW_COST_SHEET"]):
                flags["is_cost_sheet_clicked"] = 1
    return flags

if not df6.empty:
    pages_df = pd.DataFrame(df6["pages"].apply(parse_pages_json).tolist())
    df6_populated = pd.concat([df6.reset_index(drop=True), pages_df.reset_index(drop=True)], axis=1)
    ev_df = pd.DataFrame(df6["trackEvents"].apply(parse_track_events_json).tolist()) if "trackEvents" in df6.columns else pd.DataFrame()
    if not ev_df.empty:
        df6_populated = pd.concat([df6_populated, ev_df], axis=1)
    for c in [x for x in df6_populated.columns if x.startswith("is_")]:
        df6_populated[c] = df6_populated.get(c, 0).fillna(0).astype(int)
else:
    df6_populated = pd.DataFrame()

# episode start adjustment for reactivated episodes
df5["episode_start_time"] = pd.to_datetime(df5["episode_start_time"], errors="coerce")
df5["episode_end_time"] = pd.to_datetime(df5["episode_end_time"], errors="coerce")
df5 = df5.sort_values(["lead", "episode_number"]).reset_index(drop=True)
df5["prev_ep_end_time"] = df5.groupby("lead")["episode_end_time"].shift(1)
micro_offset = pd.Timedelta(milliseconds=1)
df5["episode_start_time"] = np.where(
    df5["episode_number"] > 1,
    df5["prev_ep_end_time"] + micro_offset,
    df5["episode_start_time"],
)
df5.drop(columns=["prev_ep_end_time"], errors="ignore", inplace=True)

# web aggregation per episode window
if not df6_populated.empty:
    base = df5.copy()
    base["visitorId_clean"] = base["visitorId"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
    pop = df6_populated.copy()
    pop["createdAt_dt"] = pd.to_datetime(pop["createdAt"], errors="coerce")
    pop["visitorId_clean"] = pop["visitorId"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
    m = base[["episode_id","visitorId_clean","episode_start_time","episode_end_time"]].merge(pop, on="visitorId_clean", how="inner")
    v = m[(m["createdAt_dt"] >= m["episode_start_time"]) & (m["createdAt_dt"] <= m["episode_end_time"])].copy()
    if not v.empty:
        v["cummulativeTimeSpent"] = pd.to_numeric(v.get("cummulativeTimeSpent", 0), errors="coerce").fillna(0)
        v["instanceNumber"] = pd.to_numeric(v.get("instanceNumber", 0), errors="coerce").fillna(0).astype(int)
        page_cols = [c for c in v.columns if c.endswith("_timespent")]
        flag_cols = [c for c in ["is_site_visit_book_clicked","is_whatsapp_clicked","is_brochure_downloaded","is_price_sheet_viewed","is_cost_sheet_clicked"] if c in v.columns]
        agg = {"total_web_timespent": ("cummulativeTimeSpent","sum"), "instance_min": ("instanceNumber","min"), "instance_max": ("instanceNumber","max"), "active_session_count": ("cummulativeTimeSpent", lambda s: int((s>0).sum()))}
        for c in page_cols:
            agg[c] = (c, "sum")
        for c in flag_cols:
            agg[c] = (c, lambda s: int((s>0).any()))
        web_ep = v.groupby("episode_id").agg(**agg).reset_index()
        web_ep["total_session_count"] = web_ep["instance_max"] - web_ep["instance_min"] + 1
        web_ep.drop(columns=["instance_min","instance_max"], inplace=True)
        df5 = base.merge(web_ep, on="episode_id", how="left")
    else:
        df5 = base
else:
    pass

for c in ["total_web_timespent","total_session_count","active_session_count"] + [x for x in df5.columns if x.endswith("_timespent")]:
    if c in df5.columns:
        df5[c] = df5[c].fillna(0)

# resubmissions
def calculate_episode_resubmissions(row):
    cnt = 0
    val = row.get("secondarySource")
    st = pd.to_datetime(row.get("episode_start_time"), errors="coerce")
    en = pd.to_datetime(row.get("episode_end_time"), errors="coerce")
    if pd.isna(st) or pd.isna(en) or not isinstance(val, str) or val.strip() in ("", "[]"):
        return 0
    try:
        parsed = json.loads(val)
    except Exception:
        return 0
    if not isinstance(parsed, list):
        return 0
    for item in parsed:
        if not isinstance(item, dict):
            continue
        is_react = item.get("isReactivation")
        if is_react is True or str(is_react).lower() == "true":
            continue
        dt = pd.to_datetime(item.get("date"), errors="coerce")
        if pd.notna(dt) and st <= dt <= en:
            cnt += 1
    return cnt

df5["resubmission_count_in_episode"] = df5.apply(calculate_episode_resubmissions, axis=1)
df5["is_resubmitted_in_episode"] = (df5["resubmission_count_in_episode"] > 0).astype(int)

# stage metrics from full stage history
base = df5.copy()
base["lead_clean"] = base["lead"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
stg = _leadsStageDF.copy()
stg["createdAt_dt"] = pd.to_datetime(stg["createdAt"], errors="coerce")
stg["lead_clean"] = stg["lead"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
m = base[["episode_id","lead_clean","episode_start_time","episode_end_time"]].merge(stg, on="lead_clean", how="inner")
v = m[(m["createdAt_dt"] >= m["episode_start_time"]) & (m["createdAt_dt"] <= m["episode_end_time"])].copy()
if not v.empty:
    v["is_site_visit_reason"] = v["reason"].astype(str).str.strip().str.lower().isin(["visited site","virtual site visit"])
    sv = v.groupby("episode_id")["is_site_visit_reason"].any().astype(int).reset_index(name="did_reach_site_visit_in_episode")
    v["is_mvt"] = v["isStageMovement"].astype(str).str.strip().str.lower().isin(["true","1"])
    mv = v.groupby("episode_id")["is_mvt"].sum().astype(int).reset_index(name="episode_stage_movement_count")
    sn = v[v["stage"].astype(str).str.strip() != "Not Interested"].groupby("episode_id")["stage"].last().reset_index(name="stage_before_ni")
    base = base.merge(sv, on="episode_id", how="left").merge(mv, on="episode_id", how="left").merge(sn, on="episode_id", how="left")
base["episode_duration_days"] = (base["episode_end_time"] - base["episode_start_time"]).dt.total_seconds() / 86400.0
if "did_reach_site_visit_in_episode" not in base.columns:
    base["did_reach_site_visit_in_episode"] = 0
if "episode_stage_movement_count" not in base.columns:
    base["episode_stage_movement_count"] = 0
if "stage_before_ni" not in base.columns:
    base["stage_before_ni"] = base["start_stage"] if "start_stage" in base.columns else ""
base["did_reach_site_visit_in_episode"] = pd.to_numeric(base["did_reach_site_visit_in_episode"], errors="coerce").fillna(0).astype(int)
base["episode_stage_movement_count"] = pd.to_numeric(base["episode_stage_movement_count"], errors="coerce").fillna(0).astype(int)

def resolve_episode_source_id(row):
    ep_num = row.get("episode_number")
    born = str(row.get("bornSource", "")).strip()
    start_t = pd.to_datetime(row.get("episode_start_time"), errors="coerce")
    val = row.get("secondarySource")
    if ep_num == 1 or pd.isna(start_t):
        return born or "Unknown"
    if isinstance(val, str) and val.strip() and val != "[]":
        try:
            parsed = json.loads(val)
            if isinstance(parsed, list):
                for item in reversed(parsed):
                    if not isinstance(item, dict):
                        continue
                    is_react = item.get("isReactivation")
                    if is_react is True or str(is_react).lower() == "true":
                        rec_date = pd.to_datetime(item.get("date"), errors="coerce")
                        if pd.notna(rec_date) and abs((rec_date - start_t).total_seconds()) <= 86400:
                            return str(item.get("source", "")).strip()
        except Exception:
            pass
    return born

base["episode_source"] = base.apply(resolve_episode_source_id, axis=1)

# whatsapp in episode
wa_parts = athena_batches(
    f'SELECT lead AS lead_oid, time FROM "{ATHENA_DB}"."whatsappchatmessages" WHERE (isuser = \'true\' OR isuser = \'True\' OR isuser = \'1\') AND lead IN ({{ids}})',
    qualifying_leads,
)
if not wa_parts.empty:
    wa_parts["time_dt"] = pd.to_datetime(wa_parts["time"], errors="coerce")
    wa_parts["lead_clean"] = wa_parts["lead_oid"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
    bw = base.copy()
    bw["lead_clean"] = bw["lead"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
    m = bw[["episode_id","lead_clean","episode_start_time","episode_end_time"]].merge(wa_parts, on="lead_clean", how="inner")
    v = m[(m["time_dt"] >= m["episode_start_time"]) & (m["time_dt"] <= m["episode_end_time"])]
    if not v.empty:
        wa_ep = v.groupby("episode_id").agg(
            episode_whatsapp_inbound_count=("time_dt","count"),
            first_whatsapp_time=("time_dt","min"),
            last_whatsapp_time=("time_dt","max"),
        ).reset_index()
        base = base.merge(wa_ep, on="episode_id", how="left")
if "episode_whatsapp_inbound_count" not in base.columns:
    base["episode_whatsapp_inbound_count"] = 0
base["episode_whatsapp_inbound_count"] = pd.to_numeric(base["episode_whatsapp_inbound_count"], errors="coerce").fillna(0).astype(int)
base["has_whatsapp_inbound_in_episode"] = (base["episode_whatsapp_inbound_count"] > 0).astype(int)
if "first_whatsapp_time" in base.columns:
    base["days_to_first_whatsapp_inbound"] = ((base["first_whatsapp_time"] - base["episode_start_time"]).dt.total_seconds() / 86400.0).fillna(-1.0)
    base["days_to_last_whatsapp_inbound"] = ((base["last_whatsapp_time"] - base["episode_start_time"]).dt.total_seconds() / 86400.0).fillna(-1.0)
    base.drop(columns=["first_whatsapp_time","last_whatsapp_time"], errors="ignore", inplace=True)
else:
    base["days_to_first_whatsapp_inbound"] = -1.0
    base["days_to_last_whatsapp_inbound"] = -1.0

# calls: full history for qualifying leads (not 3 month creation filter)
_callsDF = athena_batches(
    f'SELECT lead, createdat AS createdAt, direction, callstatus AS status, callduration AS duration FROM "{ATHENA_DB}"."leadcallrecords" WHERE lead IN ({{ids}})',
    qualifying_leads,
)
call_cols = [
    "lead", "episode_number", "total_answered_calls", "total_inbound_calls",
    "total_outbound_calls", "total_agent_missed_calls", "total_customer_missed_calls",
    "total_attempted_calls", "total_call_duration",
]
if _callsDF.empty:
    call_stats = pd.DataFrame(columns=call_cols)
else:
    _calls = _callsDF.copy()
    _calls["lead"] = _calls["lead"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
    _calls["call_time"] = pd.to_datetime(_calls["createdAt"], errors="coerce")
    _calls["call_status"] = _calls["status"].astype(str).str.strip().str.lower()
    _calls["call_direction"] = _calls["direction"].astype(str).str.strip().str.lower()
    _calls["call_duration"] = pd.to_numeric(_calls["duration"], errors="coerce").fillna(0)
    _eps = base.copy()
    _eps["lead"] = _eps["lead"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
    merged = _calls.merge(_eps[["lead","episode_number","episode_start_time","episode_end_time"]], on="lead", how="inner")
    merged = merged[(merged["call_time"] >= merged["episode_start_time"]) & (merged["call_time"] <= merged["episode_end_time"])].copy()
    if merged.empty:
        call_stats = pd.DataFrame(columns=call_cols)
    else:
        merged["is_answered"] = merged["call_status"].eq("answered")
        merged["is_inbound"] = merged["call_direction"].eq("inbound")
        merged["is_outbound"] = merged["call_direction"].eq("outbound")
        merged["is_agent_missed"] = merged["call_status"].eq("agent-missed")
        merged["is_customer_missed"] = merged["call_status"].eq("customer-missed")
        merged["is_attempted"] = merged["call_status"].isin(["answered","customer-missed"])
        merged["answered_duration"] = np.where(merged["is_answered"], merged["call_duration"], 0.0)
        call_stats = merged.groupby(["lead","episode_number"], as_index=False).agg(
            total_answered_calls=("is_answered","sum"),
            total_inbound_calls=("is_inbound","sum"),
            total_outbound_calls=("is_outbound","sum"),
            total_agent_missed_calls=("is_agent_missed","sum"),
            total_customer_missed_calls=("is_customer_missed","sum"),
            total_attempted_calls=("is_attempted","sum"),
            total_call_duration=("answered_duration","sum"),
        )
df_master_episode_dataset = base.merge(call_stats, on=["lead","episode_number"], how="left")
for c in ["total_answered_calls","total_inbound_calls","total_outbound_calls","total_agent_missed_calls","total_customer_missed_calls","total_attempted_calls"]:
    if c not in df_master_episode_dataset.columns:
        df_master_episode_dataset[c] = 0
    df_master_episode_dataset[c] = df_master_episode_dataset[c].fillna(0).astype(int)
if "total_call_duration" not in df_master_episode_dataset.columns:
    df_master_episode_dataset["total_call_duration"] = 0.0
df_master_episode_dataset["total_call_duration"] = df_master_episode_dataset["total_call_duration"].fillna(0.0)
df_master_episode_dataset = replace_ids_with_names(df_master_episode_dataset)
print(f"Master episode dataset: {len(df_master_episode_dataset):,} rows, {df_master_episode_dataset['lead'].nunique():,} leads")
for col in ["project", "bornSource", "source", "episode_source"]:
    if col in df_master_episode_dataset.columns:
        print(f"  {col}: {df_master_episode_dataset[col].nunique(dropna=True):,} unique  sample: {df_master_episode_dataset[col].dropna().astype(str).unique()[:6].tolist()}")

Master episode dataset: 45,115 rows, 34,735 leads
  project: 8 unique  sample: ['SPECTRA', 'SPRINGS', 'SPIRE', 'LOFT', 'LANDMARK', 'BROADWAY']
  bornSource: 32 unique  sample: ['Channel Partner', 'Web Lead', 'Phone', 'Call', 'magic-bricks', 'Social Media']
  source: 33 unique  sample: ['ASBL DB', 'Web Lead', 'Phone', 'Call', 'magic-bricks', 'Social Media']
  episode_source: 33 unique  sample: ['Channel Partner', 'Web Lead', '99-acres', 'Phone', 'Call', 'magic-bricks']

In [23]:
def feature_columns(df):
    cols = []
    for c in df.columns:
        if c in META_EXCLUDE or c.endswith(("_curr", "_prev")):
            continue
        if pd.api.types.is_numeric_dtype(df[c]):
            cols.append(c)
    return cols

def pct_change_label(prev, curr):
    if pd.isna(prev) or pd.isna(curr):
        return "Insufficient data"
    if prev == 0 and curr > 0:
        return "New Activity"
    if prev == 0 and curr == 0:
        return "No Activity"
    return f"{((curr - prev) / prev) * 100:.2f}%"

def classify_trend(values):
    clean = [v for v in values if pd.notna(v)]
    if len(clean) < 2:
        return "Insufficient data"
    deltas = [b - a for a, b in zip(clean, clean[1:])]
    if all(d > 0 for d in deltas):
        return "Increasing"
    if all(d < 0 for d in deltas):
        return "Decreasing"
    if all(abs(d) <= max(1e-9, 0.01 * abs(a)) for a, d in zip(clean, deltas)):
        return "Stable"
    return "Mixed"

# ponytail: drop <=0 then Tukey 1.5 IQR; 0/1 flags stay as rates. Upgrade to MAD if a feature stays heavy-tailed
def active_values(s):
    s = pd.to_numeric(s, errors="coerce").dropna()
    return s[s > 0]

def is_binary_feature(s):
    s = pd.to_numeric(s, errors="coerce").dropna()
    if s.empty:
        return False
    return set(s.unique()).issubset({0, 1, 0.0, 1.0})

def without_outliers(s):
    s = active_values(s)
    if len(s) < 4:
        return s
    q1, q3 = s.quantile(0.25), s.quantile(0.75)
    iqr = q3 - q1
    if iqr == 0:
        return s
    lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr
    return s[(s >= lo) & (s <= hi)]

def clean_mean(s):
    s = pd.to_numeric(s, errors="coerce").dropna()
    if s.empty:
        return np.nan
    if is_binary_feature(s):
        return float(s.mean())
    s = without_outliers(s)
    return float(s.mean()) if len(s) else np.nan

def episode_average_table(df, features=None):
    features = list(features or feature_columns(df))
    out = pd.DataFrame({"Feature": features})
    for ep in EPISODE_ORDER:
        out[ep] = [clean_mean(df.loc[df["episode_group"] == ep, f]) if f in df.columns else np.nan for f in features]
    return out

def episode_change_table(episode_avgs):
    rows = []
    transitions = list(zip(EPISODE_ORDER, EPISODE_ORDER[1:]))
    for _, row in episode_avgs.iterrows():
        rec = {"Feature": row["Feature"], "Overall Trend": classify_trend([row[e] for e in EPISODE_ORDER])}
        for ep in EPISODE_ORDER:
            rec[f"{ep} Avg"] = row[ep]
        for prev_ep, curr_ep in transitions:
            prev, curr = row[prev_ep], row[curr_ep]
            rec[f"Δ {curr_ep.split()[-1]}→{prev_ep.split()[-1]}"] = curr - prev if pd.notna(prev) and pd.notna(curr) else np.nan
            rec[f"% {curr_ep.split()[-1]}→{prev_ep.split()[-1]}"] = pct_change_label(prev, curr)
        rows.append(rec)
    return pd.DataFrame(rows)

def episode_sample_size_table(df):
    return pd.DataFrame([
        {"Episode": ep, "Unique Leads": df.loc[df["episode_group"] == ep, "lead"].nunique(), "Total Episodes": len(df[df["episode_group"] == ep])}
        for ep in EPISODE_ORDER
    ])

def source_comparison_table(episode_avgs_by_source):
    if not episode_avgs_by_source:
        return pd.DataFrame()
    base = None
    for source, tbl in episode_avgs_by_source.items():
        if tbl is None or tbl.empty:
            continue
        part = tbl.set_index("Feature").rename(columns={ep: f"{source} {ep}" for ep in EPISODE_ORDER})
        base = part if base is None else base.join(part, how="outer")
    return base.reset_index() if base is not None else pd.DataFrame()

def source_overall_average_table(df, features):
    rows = []
    for f in features:
        row = {"Feature": f, "Aggregation Level": "mean of values > 0 after dropping IQR outliers"}
        for source, flag in [("Orange", "is_orange_lead"), ("Purple", "is_purple_lead"), ("WhatsApp", "is_whatsapp_lead")]:
            sub = df[df[flag] == 1] if flag in df.columns else df.iloc[0:0]
            row[f"{source} Overall Avg"] = clean_mean(sub[f]) if f in sub.columns and len(sub) else np.nan
        rows.append(row)
    return pd.DataFrame(rows)

def participation_table(df, features):
    rows = []
    for f in features:
        if f not in df.columns:
            continue
        non, react = df[df["is_reactivated_episode"] == 0], df[df["is_reactivated_episode"] == 1]
        p_non = (non[f] > 0).mean() * 100 if len(non) else np.nan
        p_rec = (react[f] > 0).mean() * 100 if len(react) else np.nan
        rows.append({"Feature": f, "Non-Reactivated % Active": p_non, "Reactivated % Active": p_rec, "Difference (pp)": p_rec - p_non})
    return pd.DataFrame(rows)

def conditional_intensity_table(df, features):
    rows = []
    for f in features:
        if f not in df.columns:
            continue
        for label, mask in [("Non-Reactivated", df["is_reactivated_episode"] == 0), ("Reactivated", df["is_reactivated_episode"] == 1)]:
            s = without_outliers(df.loc[mask, f])
            rows.append({
                "Feature": f, "Cohort": label, "Active Episodes": len(s),
                "Mean": s.mean() if len(s) else np.nan, "Median": s.median() if len(s) else np.nan,
                "P75": s.quantile(0.75) if len(s) else np.nan, "P90": s.quantile(0.90) if len(s) else np.nan,
                "P95": s.quantile(0.95) if len(s) else np.nan,
            })
    return pd.DataFrame(rows)

def reactivation_comparison_table(df, features):
    rows = []
    non, react = df[df["is_reactivated_episode"] == 0], df[df["is_reactivated_episode"] == 1]
    for f in features:
        if f not in df.columns:
            continue
        m_non, m_rec = clean_mean(non[f]), clean_mean(react[f])
        rows.append({"Feature": f, "Non-Reactivated Avg": m_non, "Reactivated Avg": m_rec, "Absolute Change": m_rec - m_non, "% Change": pct_change_label(m_non, m_rec)})
    return pd.DataFrame(rows)

def build_within_lead_pairs(df):
    ep = df.sort_values(["lead", "episode_number"]).copy()
    ep["lead_clean"] = ep["lead"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()
    curr = ep[ep["episode_number"] >= 2].copy()
    curr["prev_episode_number"] = curr["episode_number"] - 1
    prev = ep.copy()
    return curr.merge(prev, left_on=["lead_clean", "prev_episode_number"], right_on=["lead_clean", "episode_number"], suffixes=("_curr", "_prev"))

def within_lead_pair_table(df_pairs, features):
    rows = []
    pair_labels = {2: "2 -> 1", 3: "3 -> 2", 4: "4 -> 3"}
    label_pair = lambda n: pair_labels.get(int(n), "5+ -> 4+")
    for f in features:
        prev_col, curr_col = f"{f}_prev", f"{f}_curr"
        if prev_col not in df_pairs.columns or curr_col not in df_pairs.columns:
            continue
        for pair_name, sub in df_pairs.groupby(df_pairs["episode_number_curr"].map(label_pair)):
            prev = pd.to_numeric(sub[prev_col], errors="coerce")
            curr = pd.to_numeric(sub[curr_col], errors="coerce")
            if len(prev) == 0:
                continue
            delta = curr.fillna(0.0) - prev.fillna(0.0)
            p_val = 1.0
            if len(prev.dropna()) > 1 and not (delta == 0).all():
                try:
                    p_val = stats.ttest_rel(curr.fillna(0.0), prev.fillna(0.0)).pvalue
                except Exception:
                    p_val = 1.0
            prev_avg, curr_avg = clean_mean(prev), clean_mean(curr)
            rows.append({
                "pair": pair_name, "feature": f, "active_pair_count": int(len(prev)),
                "previous_average": prev_avg, "current_average": curr_avg,
                "mean_shift": (curr_avg - prev_avg) if pd.notna(prev_avg) and pd.notna(curr_avg) else np.nan,
                "% change": pct_change_label(prev_avg, curr_avg),
                "% increased": (delta > 0).mean() * 100, "% unchanged": (delta == 0).mean() * 100,
                "% decreased": (delta < 0).mean() * 100, "test_used": "paired t-test",
                "p_value": p_val, "significance": "p<0.05" if p_val < 0.05 else "NS",
            })
    return pd.DataFrame(rows)

def stage_transition_table(df):
    if "stage_transition_path" not in df.columns:
        return pd.DataFrame()
    return pd.crosstab(df["stage_transition_path"], df["episode_group"], normalize="index").mul(100).reset_index()

def site_visit_analysis_table(df):
    cols = [c for c in ["did_reach_site_visit_in_episode", "is_site_visit_book_clicked"] if c in df.columns]
    if not cols:
        return pd.DataFrame()
    rows = []
    for ep in EPISODE_ORDER:
        sub = df[df["episode_group"] == ep]
        row = {"Episode": ep, "Episodes": len(sub)}
        for c in cols:
            row[f"{c} avg"] = clean_mean(sub[c])
            row[f"{c} % active"] = (sub[c] > 0).mean() * 100
        rows.append(row)
    return pd.DataFrame(rows)

def executive_summary(df, episode_change):
    highlights = []
    for feature in ["total_web_timespent", "total_call_duration", "episode_whatsapp_inbound_count", "resubmission_count_in_episode", "episode_stage_movement_count", "episode_duration_days"]:
        part = episode_change[episode_change["Feature"] == feature]
        if part.empty:
            continue
        highlights.append({
            "Feature": feature,
            "Overall Trend": part.iloc[0]["Overall Trend"],
            "Episode 1 Avg": part.iloc[0].get("Episode 1 Avg"),
            "Episode 5+ Avg": part.iloc[0].get("Episode 5+ Avg"),
            "Interpretation": "Episode average among values > 0 after dropping IQR outliers.",
        })
    summary = pd.DataFrame({
        "metric": ["analysis_end_date", "unique_leads", "total_episodes", "orange_leads", "purple_leads", "whatsapp_leads"],
        "value": [
            pd.Timestamp.now().strftime("%Y-%m-%d"), df["lead"].nunique(), len(df),
            int((df.drop_duplicates("lead")["is_orange_lead"] == 1).sum()) if "is_orange_lead" in df.columns else np.nan,
            int((df.drop_duplicates("lead")["is_purple_lead"] == 1).sum()) if "is_purple_lead" in df.columns else np.nan,
            int((df.drop_duplicates("lead")["is_whatsapp_lead"] == 1).sum()) if "is_whatsapp_lead" in df.columns else np.nan,
        ],
    })
    return summary, pd.DataFrame(highlights)

def _format_sheet(writer, sheet_name, df):
    df.to_excel(writer, sheet_name=sheet_name, index=False)
    ws = writer.sheets[sheet_name]
    ws.freeze_panes = "A2"
    if sheet_name == "01_Full_Episode_Data":
        ws.auto_filter.ref = ws.dimensions

def display_df(df, drop_cols=None, keep_cols=None, sort_by=None, rows=None):
    if df is None or df.empty:
        return df
    out = df.copy()
    if keep_cols is not None:
        out = out[[c for c in keep_cols if c in out.columns]]
    if drop_cols is not None:
        out = out.drop(columns=[c for c in drop_cols if c in out.columns], errors="ignore")
    if sort_by is not None:
        sort_cols = [sort_by] if isinstance(sort_by, str) else list(sort_by)
        out = out.sort_values([c for c in sort_cols if c in out.columns])
    num_cols = out.select_dtypes(include=[np.number]).columns
    out[num_cols] = out[num_cols].round(2)
    if rows is not None:
        out = out.head(rows)
    return out

def show_sheet(title, df, drop_cols=None, keep_cols=None, sort_by=None, rows=None):
    print("=" * 110)
    print(title)
    print("=" * 110)
    out = display_df(df, drop_cols=drop_cols, keep_cols=keep_cols, sort_by=sort_by, rows=rows)
    if out is None or out.empty:
        print("(empty)")
        return out
    with pd.option_context("display.max_rows", 200, "display.max_columns", 40, "display.width", 220):
        print(out.to_string(index=False))
    return out

print("OPW analysis table functions loaded.")

OPW analysis table functions loaded.

In [24]:
# Build cohort (OR logic), analysis tables, and Excel workbook
cohort_summary = build_cohort_lead_summary(
    leads_df=leads_for_cohort,
    source_df=_leadSourceDF,
    episodes_df=df_master_episode_dataset,
    analysis_end=ANALYSIS_END,
    months=ANALYSIS_MONTHS,
)
df_opw_cohort = enrich_episode_dataset(df_master_episode_dataset, cohort_summary)
df_opw_cohort = replace_ids_with_names(df_opw_cohort)
features = feature_columns(df_opw_cohort)

episode_avgs = episode_average_table(df_opw_cohort, features)
episode_change = episode_change_table(episode_avgs)
source_avgs = {
    source: episode_average_table(df_opw_cohort[df_opw_cohort[flag] == 1], features)
    for source, flag in [("Orange", "is_orange_lead"), ("Purple", "is_purple_lead"), ("WhatsApp", "is_whatsapp_lead")]
    if flag in df_opw_cohort.columns
}
pairs = build_within_lead_pairs(df_opw_cohort)
exec_summary, exec_highlights = executive_summary(df_opw_cohort, episode_change)

cohort_summary_df = pd.DataFrame({
    "metric": [
        "total_unique_leads", "total_episodes", "episode_1_count", "episode_2_count",
        "episode_3_count", "episode_4_count", "episode_5_plus_count",
        "orange_leads", "purple_leads", "whatsapp_leads",
    ],
    "value": [
        df_opw_cohort["lead"].nunique(), len(df_opw_cohort),
        len(df_opw_cohort[df_opw_cohort["episode_group"] == "Episode 1"]),
        len(df_opw_cohort[df_opw_cohort["episode_group"] == "Episode 2"]),
        len(df_opw_cohort[df_opw_cohort["episode_group"] == "Episode 3"]),
        len(df_opw_cohort[df_opw_cohort["episode_group"] == "Episode 4"]),
        len(df_opw_cohort[df_opw_cohort["episode_group"] == "Episode 5+"]),
        int(df_opw_cohort.drop_duplicates("lead")["is_orange_lead"].sum()) if "is_orange_lead" in df_opw_cohort.columns else 0,
        int(df_opw_cohort.drop_duplicates("lead")["is_purple_lead"].sum()) if "is_purple_lead" in df_opw_cohort.columns else 0,
        int(df_opw_cohort.drop_duplicates("lead")["is_whatsapp_lead"].sum()) if "is_whatsapp_lead" in df_opw_cohort.columns else 0,
    ],
})
episode_sample_size = episode_sample_size_table(df_opw_cohort)
source_comparison = source_comparison_table(source_avgs)
source_overall_avg = source_overall_average_table(df_opw_cohort, features)
reactivation_comparison = reactivation_comparison_table(df_opw_cohort, features)
participation = participation_table(df_opw_cohort, features)
conditional_intensity = conditional_intensity_table(df_opw_cohort, features)
within_lead_pairs = within_lead_pair_table(pairs, features)
stage_transitions = stage_transition_table(df_opw_cohort)
site_visit_analysis = site_visit_analysis_table(df_opw_cohort)
executive_summary_df = pd.concat([exec_summary, pd.DataFrame([{}]), exec_highlights], ignore_index=True)

OUTPUT_XLSX = Path("OPW_Episode_Cohort_Analysis1.xlsx")
with pd.ExcelWriter(OUTPUT_XLSX, engine="openpyxl") as writer:
    _format_sheet(writer, "01_Full_Episode_Data", df_opw_cohort)
    _format_sheet(writer, "02_Cohort_Summary", cohort_summary_df)
    _format_sheet(writer, "03_Episode_Averages", episode_avgs)
    _format_sheet(writer, "04_Episode_Change", episode_change)
    _format_sheet(writer, "05_Episode_Sample_Size", episode_sample_size)
    for source, sheet in [("Orange", "06_Orange_Episode_Avg"), ("Purple", "07_Purple_Episode_Avg"), ("WhatsApp", "08_WhatsApp_Episode_Avg")]:
        if source in source_avgs:
            _format_sheet(writer, sheet, source_avgs[source])
    _format_sheet(writer, "09_Source_Comparison", source_comparison)
    _format_sheet(writer, "09b_Source_Overall_Avg", source_overall_avg)
    _format_sheet(writer, "10_Reactivation_Comparison", reactivation_comparison)
    _format_sheet(writer, "11_Participation", participation)
    _format_sheet(writer, "12_Conditional_Intensity", conditional_intensity)
    _format_sheet(writer, "13_Within_Lead_Pairs", within_lead_pairs)
    _format_sheet(writer, "14_Stage_Transitions", stage_transitions)
    _format_sheet(writer, "15_Site_Visit_Analysis", site_visit_analysis)
    _format_sheet(writer, "16_Executive_Summary", executive_summary_df)

print("Cohort filter logic: OR across Orange / Purple / WhatsApp qualifying events")
print("Orange/Purple: timestamp event in 6-month window (any original birth source)")
print("WhatsApp: born OR reactivated OR resubmitted in 6-month window (any original birth source for reactivation/resubmission)")
print(f"  Orange leads:   {(cohort_summary['is_orange_lead'] == 1).sum():,}")
print(f"  Purple leads:   {(cohort_summary['is_purple_lead'] == 1).sum():,}")
print(f"  WhatsApp leads: {(cohort_summary['is_whatsapp_lead'] == 1).sum():,}")
print(f"  Multi-channel:  {(cohort_summary[['is_orange_lead','is_purple_lead','is_whatsapp_lead']].sum(axis=1) > 1).sum():,}")
print(f"Qualified leads: {df_opw_cohort['lead'].nunique():,}")
print(f"Qualified episodes: {len(df_opw_cohort):,}")
print(f"Workbook written to: {OUTPUT_XLSX.resolve()}")

Cohort filter logic: OR across Orange / Purple / WhatsApp qualifying events
Orange/Purple: timestamp event in 6-month window (any original birth source)
WhatsApp: born OR reactivated OR resubmitted in 6-month window (any original birth source for reactivation/resubmission)
  Orange leads:   2,759
  Purple leads:   31,303
  WhatsApp leads: 34,481
  Multi-channel:  31,080
Qualified leads: 34,735
Qualified episodes: 45,115
Workbook written to: /Users/lekhanigam/RM Feature Analysis/OPW_Episode_Cohort_Analysis1.xlsx

In [25]:
# 01 — full episode dataset (preview; Excel has all rows)
full_data_preview_cols = [
    "lead", "episode_number", "episode_group", "episode_start_time", "episode_end_time",
    "project", "bornSource", "source", "episode_source", "start_stage", "end_stage",
    "total_web_timespent", "active_session_count", "episode_whatsapp_inbound_count",
    "total_answered_calls", "total_outbound_calls", "pickup_ratio",
    "resubmission_count_in_episode", "did_reach_site_visit_in_episode",
    "episode_stage_movement_count", "episode_duration_days",
    "is_orange_lead", "is_purple_lead", "is_whatsapp_lead",
]
print("=" * 110)
print("01_Full_Episode_Data")
print("=" * 110)
print(f"Rows: {len(df_opw_cohort):,}  ·  Columns in Excel: {df_opw_cohort.shape[1]}")
print(f"Notebook preview columns: {full_data_preview_cols}")
display_df(df_opw_cohort, keep_cols=full_data_preview_cols, rows=10)

==============================================================================================================
01_Full_Episode_Data
==============================================================================================================
Rows: 45,115  ·  Columns in Excel: 73
Notebook preview columns: ['lead', 'episode_number', 'episode_group', 'episode_start_time', 'episode_end_time', 'project', 'bornSource', 'source', 'episode_source', 'start_stage', 'end_stage', 'total_web_timespent', 'active_session_count', 'episode_whatsapp_inbound_count', 'total_answered_calls', 'total_outbound_calls', 'pickup_ratio', 'resubmission_count_in_episode', 'did_reach_site_visit_in_episode', 'episode_stage_movement_count', 'episode_duration_days', 'is_orange_lead', 'is_purple_lead', 'is_whatsapp_lead']

,lead,episode_number,episode_group,episode_start_time,episode_end_time,project,bornSource,source,episode_source,start_stage,...,total_answered_calls,total_outbound_calls,pickup_ratio,resubmission_count_in_episode,did_reach_site_visit_in_episode,episode_stage_movement_count,episode_duration_days,is_orange_lead,is_purple_lead,is_whatsapp_lead
0,6153206feb9f036ae4ee6853,1,Episode 1,2021-10-02 04:19:00.567,2023-07-07 03:29:09.776,SPECTRA,Channel Partner,ASBL DB,Channel Partner,New Lead,...,0,0,0.00,0,0,2,642.97,0,0,1
1,6154689550c5a7227fe16af9,1,Episode 1,2021-10-01 06:55:11.911,2023-07-07 03:29:18.199,SPRINGS,Channel Partner,ASBL DB,Channel Partner,New Lead,...,0,0,0.00,0,0,2,643.86,0,0,1
2,6154689550c5a7227fe16af9,2,Episode 2,2023-07-07 03:29:18.200,2026-04-10 07:20:33.512,SPRINGS,Channel Partner,ASBL DB,Channel Partner,New Lead,...,0,1,0.00,0,0,1,1008.16,0,0,1
3,615468b950c5a7227fe16d74,1,Episode 1,2021-10-01 06:55:14.716,2023-07-07 03:29:11.636,SPRINGS,Channel Partner,ASBL DB,Channel Partner,New Lead,...,0,0,0.00,0,0,2,643.86,0,0,1
4,615468b950c5a7227fe16d74,2,Episode 2,2023-07-07 03:29:11.637,2026-02-20 10:35:46.634,SPRINGS,Channel Partner,ASBL DB,Channel Partner,New Lead,...,0,1,0.00,0,0,2,959.30,0,0,1
5,615468b950c5a7227fe16d74,3,Episode 3,2026-02-20 10:35:46.635,2026-04-04 08:12:48.110,SPRINGS,Channel Partner,ASBL DB,Channel Partner,New Lead,...,0,3,0.00,0,0,3,42.90,0,0,1
6,616340b0dc442c4c16401cb5,1,Episode 1,2021-10-10 19:36:16.347,2023-07-07 03:28:47.984,SPECTRA,Web Lead,Web Lead,Web Lead,Lead Initiated,...,2,2,0.50,0,0,2,634.33,0,0,1
7,616340b0dc442c4c16401cb5,2,Episode 2,2023-07-07 03:28:47.985,2025-05-22 10:46:37.282,SPECTRA,Web Lead,Web Lead,Web Lead,Lead Initiated,...,0,8,0.00,0,0,2,685.30,0,0,1
8,616340b0dc442c4c16401cb5,3,Episode 3,2025-05-22 10:46:37.283,2026-05-14 09:47:16.313,SPECTRA,Web Lead,Web Lead,Web Lead,Lead Initiated,...,1,13,0.17,0,0,2,356.96,0,0,1
9,6166669236e6276bd6f6d0e3,1,Episode 1,2021-10-13 04:54:42.623,2023-07-07 03:28:47.477,SPECTRA,Web Lead,Web Lead,Web Lead,Lead Initiated,...,1,1,1.00,0,0,2,631.94,0,0,1

In [26]:
# 02 + 05 — cohort counts and episode sample sizes
show_sheet("02_Cohort_Summary", cohort_summary_df)
show_sheet("05_Episode_Sample_Size", episode_sample_size)

==============================================================================================================
02_Cohort_Summary
==============================================================================================================
              metric  value
  total_unique_leads  34735
      total_episodes  45115
     episode_1_count  34735
     episode_2_count   7608
     episode_3_count   1676
     episode_4_count    505
episode_5_plus_count    591
        orange_leads   2759
        purple_leads  31303
      whatsapp_leads  34481
==============================================================================================================
05_Episode_Sample_Size
==============================================================================================================
   Episode  Unique Leads  Total Episodes
 Episode 1         34735           34735
 Episode 2          7608            7608
 Episode 3          1676            1676
 Episode 4           505             505
Episode 5+           214             591

      Episode  Unique Leads  Total Episodes
0   Episode 1         34735           34735
1   Episode 2          7608            7608
2   Episode 3          1676            1676
3   Episode 4           505             505
4  Episode 5+           214             591

In [27]:
# 03 + 04 — View A episode averages and episode-to-episode change
print("Averages exclude zeros and IQR outliers; 0/1 flags stay as rates.")
show_sheet("03_Episode_Averages", episode_avgs)
show_sheet("04_Episode_Change", episode_change)

Averages exclude zeros and IQR outliers; 0/1 flags stay as rates.
==============================================================================================================
03_Episode_Averages
==============================================================================================================
                        Feature  Episode 1  Episode 2  Episode 3  Episode 4  Episode 5+
          total_stage_movements       8.67       7.24       7.28       7.44        6.11
         is_reactivated_episode       0.22       0.22       0.30       0.42        0.64
            total_web_timespent      53.34     124.45     401.71     434.04     3081.09
           active_session_count       1.34       1.72       2.27       2.39       14.28
                 home_timespent      34.17      73.97     171.39     190.54      997.22
                price_timespent      69.00     166.96     203.80     183.02      708.87
                 plan_timespent      63.61     168.10     276.04     356.23      964.52
             location_timespent      34.69      76.35     161.75     193.08      428.74
            amenities_timespent      22.01      98.84     264.16     281.63      418.52
                media_timespent     102.17      86.46     349.74     797.74      888.01
       specifications_timespent      81.50     309.06     455.29     216.22      147.51
     is_site_visit_book_clicked       0.13       0.08       0.12       0.08        0.26
            is_whatsapp_clicked       0.14       0.14       0.16       0.15        0.32
         is_brochure_downloaded       0.45       0.47       0.61       0.60        0.69
          is_price_sheet_viewed       0.22       0.34       0.50       0.62        0.77
          is_cost_sheet_clicked       0.04       0.06       0.10       0.10        0.17
            total_session_count       1.42       1.87       2.33       2.57       15.95
  resubmission_count_in_episode       1.48       1.60       1.94       4.22        1.35
      is_resubmitted_in_episode       0.03       0.03       0.06       0.07        0.14
did_reach_site_visit_in_episode       0.01       0.02       0.03       0.04        0.05
   episode_stage_movement_count       2.66       2.08       2.05       2.06        2.04
          episode_duration_days       4.30     123.86      79.94      68.20       35.65
 episode_whatsapp_inbound_count       1.27       2.51       3.06       3.10        3.87
has_whatsapp_inbound_in_episode       0.09       0.51       0.46       0.47        0.41
 days_to_first_whatsapp_inbound       0.00     157.69     108.23      88.24       37.79
  days_to_last_whatsapp_inbound       0.01     200.05     151.77     119.26       67.09
           total_answered_calls       1.34       1.30       1.34       1.45        1.37
            total_inbound_calls       1.31       1.32       1.41       1.44        1.88
           total_outbound_calls       5.46       4.91       4.90       5.04        3.57
       total_agent_missed_calls       2.90       2.41       2.40       2.53        2.02
    total_customer_missed_calls       3.79       3.26       3.40       3.30        2.99
          total_attempted_calls       3.60       3.20       3.34       3.32        2.96
            total_call_duration      42.28      37.29      46.80      47.56       55.03
                   pickup_ratio       0.70       0.67       0.69       0.69        0.72
               avg_web_activity      37.05      81.35     121.89     139.96      161.30
==============================================================================================================
04_Episode_Change
==============================================================================================================
                        Feature Overall Trend  Episode 1 Avg  Episode 2 Avg  Episode 3 Avg  Episode 4 Avg  Episode 5+ Avg  Δ 2→1        % 2→1  Δ 3→2   % 3→2   Δ 4→3   % 4→3  Δ 5+→4  % 5+→4
          total_stage_movements         Mixed           8.67           7.24           7.28           7.44            6.11  -1.42      -16.40%   0.04   0.50%    0.16   2.21%   -1.33 -17.87%
         is_reactivated_episode    Increasing           0.22           0.22           0.30           0.42            0.64   0.00        0.58%   0.08  36.78%    0.12  40.64%    0.21  50.53%
            total_web_timespent    Increasing          53.34         124.45         401.71         434.04         3081.09  71.11      133.33% 277.26 222.79%   32.32   8.05% 2647.05 609.87%
           active_session_count    Increasing           1.34           1.72           2.27           2.39           14.28   0.39       28.89%   0.55  31.75%    0.12   5.51%   11.89 496.78%
                 home_timespent    Increasing          34.17          73.97         171.39         190.54          997.22  39.80      116.47%  97.41 131.69%   19.16  11.18%  806.68 423.36%
                price_timespent         Mixed          69.00         166.96         203.80         183.02          708.87  97.95      141.95%  36.84  22.07%  -20.78 -10.19%  525.86 287.32%
                 plan_timespent    Increasing          63.61         168.10         276.04         356.23          964.52 104.49      164.27% 107.94  64.21%   80.19  29.05%  608.29 170.76%
             location_timespent    Increasing          34.69          76.35         161.75         193.08          428.74  41.66      120.08%  85.40 111.86%   31.34  19.37%  235.65 122.05%
            amenities_timespent    Increasing          22.01          98.84         264.16         281.63          418.52  76.83      348.99% 165.32 167.26%   17.47   6.61%  136.89  48.61%
                media_timespent         Mixed         102.17          86.46         349.74         797.74          888.01 -15.71      -15.38% 263.28 304.52%  448.00 128.09%   90.27  11.32%
       specifications_timespent         Mixed          81.50         309.06         455.29         216.22          147.51 227.57      279.24% 146.23  47.31% -239.07 -52.51%  -68.72 -31.78%
     is_site_visit_book_clicked         Mixed           0.13           0.08           0.12           0.08            0.26  -0.05      -37.39%   0.04  43.03%   -0.04 -34.39%    0.18 234.44%
            is_whatsapp_clicked         Mixed           0.14           0.14           0.16           0.15            0.32  -0.01       -4.68%   0.02  16.58%   -0.00  -3.01%    0.17 107.68%
         is_brochure_downloaded         Mixed           0.45           0.47           0.61           0.60            0.69   0.02        3.57%   0.15  31.37%   -0.01  -1.83%    0.09  15.00%
          is_price_sheet_viewed    Increasing           0.22           0.34           0.50           0.62            0.77   0.12       53.51%   0.15  44.93%    0.12  23.93%    0.15  24.74%
          is_cost_sheet_clicked         Mixed           0.04           0.06           0.10           0.10            0.17   0.02       61.68%   0.05  80.30%   -0.00  -0.85%    0.07  65.87%
            total_session_count    Increasing           1.42           1.87           2.33           2.57           15.95   0.45       31.85%   0.46  24.42%    0.24  10.37%   13.38 520.85%
  resubmission_count_in_episode         Mixed           1.48           1.60           1.94           4.22            1.35   0.12        8.06%   0.34  21.06%    2.27 117.14%   -2.86 -67.93%
      is_resubmitted_in_episode         Mixed           0.03           0.03           0.06           0.07            0.14  -0.00       -4.10%   0.03  83.36%    0.01  19.22%    0.07  96.30%
did_reach_site_visit_in_episode    Increasing           0.01           0.02           0.03           0.04            0.05   0.01       59.38%   0.01  61.07%    0.01  32.75%    0.01  20.40%
   episode_stage_movement_count         Mixed           2.66           2.08           2.05           2.06            2.04  -0.59      -22.11%  -0.02  -1.02%    0.01   0.44%   -0.02  -1.10%
          episode_duration_days         Mixed           4.30         123.86          79.94          68.20           35.65 119.55     2777.13% -43.92 -35.46%  -11.74 -14.69%  -32.55 -47.72%
 episode_whatsapp_inbound_count    Increasing           1.27           2.51           3.06           3.10            3.87   1.24       98.09%   0.56  22.24%    0.03   1.11%    0.77  24.87%
has_whatsapp_inbound_in_episode         Mixed           0.09           0.51           0.46           0.47            0.41   0.42      462.30%  -0.05  -9.75%    0.00   0.63%   -0.05 -11.64%
 days_to_first_whatsapp_inbound         Mixed           0.00         157.69         108.23          88.24           37.79 157.69 40504850.14% -49.46 -31.37%  -19.99 -18.47%  -50.45 -57.17%
  days_to_last_whatsapp_inbound         Mixed           0.01         200.05         151.77         119.26           67.09 200.04  1998945.18% -48.27 -24.13%  -32.51 -21.42%  -52.18 -43.75%
           total_answered_calls         Mixed           1.34           1.30           1.34           1.45            1.37  -0.03       -2.49%   0.04   3.09%    0.10   7.73%   -0.08  -5.27%
            total_inbound_calls    Increasing           1.31           1.32           1.41           1.44            1.88   0.02        1.22%   0.09   6.78%    0.03   2.36%    0.43  29.81%
           total_outbound_calls         Mixed           5.46           4.91           4.90           5.04            3.57  -0.54       -9.93%  -0.02  -0.32%    0.14   2.86%   -1.47 -29.23%
       total_agent_missed_calls         Mixed           2.90           2.41           2.40           2.53            2.02  -0.49      -16.79%  -0.01  -0.34%    0.12   5.17%   -0.50 -19.89%
    total_customer_missed_calls         Mixed           3.79           3.26           3.40           3.30            2.99  -0.52      -13.85%   0.13   4.02%   -0.10  -2.96%   -0.30  -9.20%
          total_attempted_calls         Mixed           3.60           3.20           3.34           3.32            2.96  -0.41      -11.29%   0.14   4.43%   -0.02  -0.54%   -0.35 -10.66%
            total_call_duration         Mixed          42.28          37.29          46.80          47.56           55.03  -4.99      -11.81%   9.51  25.50%    0.76   1.63%    7.47  15.72%
                   pickup_ratio         Mixed           0.70           0.67           0.69           0.69            0.72  -0.04       -5.07%   0.02   2.94%    0.00   0.24%    0.03   5.05%
               avg_web_activity    Increasing          37.05          81.35         121.89         139.96          161.30  44.30      119.57%  40.54  49.84%   18.07  14.83%   21.34  15.25%

,Feature,Overall Trend,Episode 1 Avg,Episode 2 Avg,Episode 3 Avg,Episode 4 Avg,Episode 5+ Avg,Δ 2→1,% 2→1,Δ 3→2,% 3→2,Δ 4→3,% 4→3,Δ 5+→4,% 5+→4
0,total_stage_movements,Mixed,8.67,7.24,7.28,7.44,6.11,-1.42,-16.40%,0.04,0.50%,0.16,2.21%,-1.33,-17.87%
1,is_reactivated_episode,Increasing,0.22,0.22,0.30,0.42,0.64,0.00,0.58%,0.08,36.78%,0.12,40.64%,0.21,50.53%
2,total_web_timespent,Increasing,53.34,124.45,401.71,434.04,3081.09,71.11,133.33%,277.26,222.79%,32.32,8.05%,2647.05,609.87%
3,active_session_count,Increasing,1.34,1.72,2.27,2.39,14.28,0.39,28.89%,0.55,31.75%,0.12,5.51%,11.89,496.78%
4,home_timespent,Increasing,34.17,73.97,171.39,190.54,997.22,39.80,116.47%,97.41,131.69%,19.16,11.18%,806.68,423.36%
5,price_timespent,Mixed,69.00,166.96,203.80,183.02,708.87,97.95,141.95%,36.84,22.07%,-20.78,-10.19%,525.86,287.32%
6,plan_timespent,Increasing,63.61,168.10,276.04,356.23,964.52,104.49,164.27%,107.94,64.21%,80.19,29.05%,608.29,170.76%
7,location_timespent,Increasing,34.69,76.35,161.75,193.08,428.74,41.66,120.08%,85.40,111.86%,31.34,19.37%,235.65,122.05%
8,amenities_timespent,Increasing,22.01,98.84,264.16,281.63,418.52,76.83,348.99%,165.32,167.26%,17.47,6.61%,136.89,48.61%
9,media_timespent,Mixed,102.17,86.46,349.74,797.74,888.01,-15.71,-15.38%,263.28,304.52%,448.00,128.09%,90.27,11.32%
10,specifications_timespent,Mixed,81.50,309.06,455.29,216.22,147.51,227.57,279.24%,146.23,47.31%,-239.07,-52.51%,-68.72,-31.78%
11,is_site_visit_book_clicked,Mixed,0.13,0.08,0.12,0.08,0.26,-0.05,-37.39%,0.04,43.03%,-0.04,-34.39%,0.18,234.44%
12,is_whatsapp_clicked,Mixed,0.14,0.14,0.16,0.15,0.32,-0.01,-4.68%,0.02,16.58%,-0.00,-3.01%,0.17,107.68%
13,is_brochure_downloaded,Mixed,0.45,0.47,0.61,0.60,0.69,0.02,3.57%,0.15,31.37%,-0.01,-1.83%,0.09,15.00%
14,is_price_sheet_viewed,Increasing,0.22,0.34,0.50,0.62,0.77,0.12,53.51%,0.15,44.93%,0.12,23.93%,0.15,24.74%
15,is_cost_sheet_clicked,Mixed,0.04,0.06,0.10,0.10,0.17,0.02,61.68%,0.05,80.30%,-0.00,-0.85%,0.07,65.87%
16,total_session_count,Increasing,1.42,1.87,2.33,2.57,15.95,0.45,31.85%,0.46,24.42%,0.24,10.37%,13.38,520.85%
17,resubmission_count_in_episode,Mixed,1.48,1.60,1.94,4.22,1.35,0.12,8.06%,0.34,21.06%,2.27,117.14%,-2.86,-67.93%
18,is_resubmitted_in_episode,Mixed,0.03,0.03,0.06,0.07,0.14,-0.00,-4.10%,0.03,83.36%,0.01,19.22%,0.07,96.30%
19,did_reach_site_visit_in_episode,Increasing,0.01,0.02,0.03,0.04,0.05,0.01,59.38%,0.01,61.07%,0.01,32.75%,0.01,20.40%
20,episode_stage_movement_count,Mixed,2.66,2.08,2.05,2.06,2.04,-0.59,-22.11%,-0.02,-1.02%,0.01,0.44%,-0.02,-1.10%
21,episode_duration_days,Mixed,4.30,123.86,79.94,68.20,35.65,119.55,2777.13%,-43.92,-35.46%,-11.74,-14.69%,-32.55,-47.72%
22,episode_whatsapp_inbound_count,Increasing,1.27,2.51,3.06,3.10,3.87,1.24,98.09%,0.56,22.24%,0.03,1.11%,0.77,24.87%
23,has_whatsapp_inbound_in_episode,Mixed,0.09,0.51,0.46,0.47,0.41,0.42,462.30%,-0.05,-9.75%,0.00,0.63%,-0.05,-11.64%
24,days_to_first_whatsapp_inbound,Mixed,0.00,157.69,108.23,88.24,37.79,157.69,40504850.14%,-49.46,-31.37%,-19.99,-18.47%,-50.45,-57.17%
25,days_to_last_whatsapp_inbound,Mixed,0.01,200.05,151.77,119.26,67.09,200.04,1998945.18%,-48.27,-24.13%,-32.51,-21.42%,-52.18,-43.75%
26,total_answered_calls,Mixed,1.34,1.30,1.34,1.45,1.37,-0.03,-2.49%,0.04,3.09%,0.10,7.73%,-0.08,-5.27%
27,total_inbound_calls,Increasing,1.31,1.32,1.41,1.44,1.88,0.02,1.22%,0.09,6.78%,0.03,2.36%,0.43,29.81%
28,total_outbound_calls,Mixed,5.46,4.91,4.90,5.04,3.57,-0.54,-9.93%,-0.02,-0.32%,0.14,2.86%,-1.47,-29.23%
29,total_agent_missed_calls,Mixed,2.90,2.41,2.40,2.53,2.02,-0.49,-16.79%,-0.01,-0.34%,0.12,5.17%,-0.50,-19.89%
30,total_customer_missed_calls,Mixed,3.79,3.26,3.40,3.30,2.99,-0.52,-13.85%,0.13,4.02%,-0.10,-2.96%,-0.30,-9.20%
31,total_attempted_calls,Mixed,3.60,3.20,3.34,3.32,2.96,-0.41,-11.29%,0.14,4.43%,-0.02,-0.54%,-0.35,-10.66%
32,total_call_duration,Mixed,42.28,37.29,46.80,47.56,55.03,-4.99,-11.81%,9.51,25.50%,0.76,1.63%,7.47,15.72%
33,pickup_ratio,Mixed,0.70,0.67,0.69,0.69,0.72,-0.04,-5.07%,0.02,2.94%,0.00,0.24%,0.03,5.05%
34,avg_web_activity,Increasing,37.05,81.35,121.89,139.96,161.30,44.30,119.57%,40.54,49.84%,18.07,14.83%,21.34,15.25%

In [28]:
# 06–09 — Orange / Purple / WhatsApp source slices
for source, sheet in [("Orange", "06_Orange_Episode_Avg"), ("Purple", "07_Purple_Episode_Avg"), ("WhatsApp", "08_WhatsApp_Episode_Avg")]:
    if source in source_avgs:
        show_sheet(sheet, source_avgs[source])
show_sheet("09_Source_Comparison", source_comparison)
show_sheet("09b_Source_Overall_Avg", source_overall_avg, drop_cols=["Aggregation Level"])

==============================================================================================================
06_Orange_Episode_Avg
==============================================================================================================
                        Feature  Episode 1  Episode 2  Episode 3  Episode 4  Episode 5+
          total_stage_movements      11.73       8.33       8.01       8.50        8.40
         is_reactivated_episode       0.34       0.31       0.41       0.46        0.66
            total_web_timespent     112.50     164.78     182.31     630.71     2290.87
           active_session_count       1.37       1.38       2.35       2.00       13.19
                 home_timespent      62.30      77.11     111.57     215.62     1156.87
                price_timespent      93.15     167.80     183.52     170.34     1513.71
                 plan_timespent     115.60     132.14     173.24     169.19     1658.24
             location_timespent      23.17     181.32      15.77     172.74      373.39
            amenities_timespent      24.91      51.87       4.23     100.70      284.14
                media_timespent     129.33    1173.88     404.88     105.17      937.11
       specifications_timespent      20.29     154.33       5.64      73.12      665.26
     is_site_visit_book_clicked       0.16       0.09       0.00       0.00        0.19
            is_whatsapp_clicked       0.16       0.11       0.06       0.19        0.31
         is_brochure_downloaded       0.40       0.51       0.45       0.52        0.60
          is_price_sheet_viewed       0.39       0.45       0.48       0.67        0.74
          is_cost_sheet_clicked       0.10       0.16       0.13       0.19        0.14
            total_session_count       1.41       1.50       2.18       2.17       16.08
  resubmission_count_in_episode       1.47       1.18       1.30       2.00        1.29
      is_resubmitted_in_episode       0.08       0.08       0.10       0.08        0.22
did_reach_site_visit_in_episode       0.04       0.04       0.06       0.04        0.02
   episode_stage_movement_count       2.78       2.14       2.09       2.08        2.04
          episode_duration_days       6.33     106.55      62.20      55.00       29.01
 episode_whatsapp_inbound_count       4.27       6.07       5.05       6.36        6.94
has_whatsapp_inbound_in_episode       0.06       0.51       0.49       0.49        0.47
 days_to_first_whatsapp_inbound       4.81     137.27      90.82      76.08       20.94
  days_to_last_whatsapp_inbound      13.12     180.21     124.17      92.52       41.32
           total_answered_calls       1.92       1.38       1.35       1.38        1.97
            total_inbound_calls       1.35       1.26       1.49       1.37        1.35
           total_outbound_calls       7.20       5.55       5.09       5.26        4.81
       total_agent_missed_calls       3.43       2.64       2.37       2.64        2.13
    total_customer_missed_calls       4.05       3.24       3.43       3.61        3.65
          total_attempted_calls       4.46       3.40       3.57       3.59        4.04
            total_call_duration      91.44      50.77      61.53      44.58       78.39
                   pickup_ratio       0.65       0.66       0.69       0.64        0.65
               avg_web_activity      71.67     141.45     132.81     157.00      165.30
==============================================================================================================
07_Purple_Episode_Avg
==============================================================================================================
                        Feature  Episode 1  Episode 2  Episode 3  Episode 4  Episode 5+
          total_stage_movements       8.81       7.27       7.26       7.52        6.19
         is_reactivated_episode       0.23       0.21       0.29       0.41        0.64
            total_web_timespent      53.27     106.62     171.94     408.38     5372.33
           active_session_count       1.34       1.61       1.85       2.04       18.77
                 home_timespent      33.97      56.93      89.87     198.59     1568.44
                price_timespent      66.26     159.98     150.32     201.99     1409.98
                 plan_timespent      70.37     153.30     174.02     307.93     2012.53
             location_timespent      33.87      77.52     250.74     175.07      514.29
            amenities_timespent      25.22      78.88     226.81     147.13      392.94
                media_timespent     109.48      78.60     266.64    1452.50      939.43
       specifications_timespent      94.01     275.13     458.67     174.05      159.15
     is_site_visit_book_clicked       0.12       0.07       0.10       0.06        0.29
            is_whatsapp_clicked       0.14       0.12       0.16       0.15        0.35
         is_brochure_downloaded       0.48       0.47       0.59       0.62        0.76
          is_price_sheet_viewed       0.23       0.32       0.45       0.61        0.78
          is_cost_sheet_clicked       0.03       0.05       0.08       0.11        0.20
            total_session_count       1.42       1.86       2.14       2.20       22.17
  resubmission_count_in_episode       1.49       1.62       1.90       4.58        1.38
      is_resubmitted_in_episode       0.03       0.03       0.06       0.07        0.15
did_reach_site_visit_in_episode       0.01       0.02       0.03       0.04        0.04
   episode_stage_movement_count       2.68       2.06       2.04       2.04        2.02
          episode_duration_days       4.51     121.81      80.51      77.13       34.78
 episode_whatsapp_inbound_count       1.99       2.46       3.04       3.07        4.05
has_whatsapp_inbound_in_episode       0.04       0.53       0.48       0.50        0.45
 days_to_first_whatsapp_inbound      12.20     158.75     110.81      91.77       33.94
  days_to_last_whatsapp_inbound      75.28     200.22     155.86     127.65       66.59
           total_answered_calls       1.35       1.31       1.34       1.45        1.38
            total_inbound_calls       1.29       1.32       1.43       1.43        1.38
           total_outbound_calls       5.57       4.93       4.92       5.11        3.59
       total_agent_missed_calls       3.14       2.41       2.40       2.54        2.00
    total_customer_missed_calls       3.83       3.27       3.40       3.35        2.98
          total_attempted_calls       3.66       3.20       3.34       3.34        2.98
            total_call_duration      43.20      36.92      44.41      47.52       53.85
                   pickup_ratio       0.70       0.67       0.68       0.69        0.72
               avg_web_activity      35.39      68.53      85.30     123.01      151.11
==============================================================================================================
08_WhatsApp_Episode_Avg
==============================================================================================================
                        Feature  Episode 1  Episode 2  Episode 3  Episode 4  Episode 5+
          total_stage_movements       8.66       7.25       7.28       7.45        6.18
         is_reactivated_episode       0.22       0.22       0.30       0.42        0.63
            total_web_timespent      53.63     124.03     397.00     438.82     3005.35
           active_session_count       1.34       1.72       2.11       2.40       13.33
                 home_timespent      34.38      73.36     156.71     194.37     1012.23
                price_timespent      69.44     167.41     203.80     183.02      721.62
                 plan_timespent      62.56     164.57     312.70     356.23     1206.58
             location_timespent      34.48     115.62     161.75     193.08      500.48
            amenities_timespent      21.75      95.04     264.16     281.63      448.65
                media_timespent     103.00      87.27     621.51     846.36      997.22
       specifications_timespent      81.45     342.09     472.99     216.22      218.51
     is_site_visit_book_clicked       0.13       0.08       0.12       0.08        0.27
            is_whatsapp_clicked       0.14       0.14       0.16       0.16        0.33
         is_brochure_downloaded       0.46       0.46       0.61       0.61        0.67
          is_price_sheet_viewed       0.23       0.34       0.50       0.62        0.76
          is_cost_sheet_clicked       0.04       0.06       0.10       0.10        0.19
            total_session_count       1.43       1.87       2.19       2.58       14.89
  resubmission_count_in_episode       1.49       1.60       1.94       4.22        1.33
      is_resubmitted_in_episode       0.04       0.03       0.06       0.07        0.14
did_reach_site_visit_in_episode       0.01       0.02       0.03       0.04        0.05
   episode_stage_movement_count       2.66       2.08       2.05       2.06        2.04
          episode_duration_days       4.28     124.00      80.10      68.34       35.99
 episode_whatsapp_inbound_count       1.25       2.50       3.07       3.10        3.37
has_whatsapp_inbound_in_episode       0.08       0.51       0.46       0.47        0.40
 days_to_first_whatsapp_inbound       0.00     157.73     108.32      88.24       40.32
  days_to_last_whatsapp_inbound       0.00     200.13     151.92     119.26       68.70
           total_answered_calls       1.34       1.30       1.35       1.45        1.38
            total_inbound_calls       1.31       1.32       1.41       1.44        1.88
           total_outbound_calls       5.46       4.92       4.90       5.04        3.66
       total_agent_missed_calls       2.89       2.41       2.40       2.53        2.06
    total_customer_missed_calls       3.79       3.27       3.39       3.30        3.01
          total_attempted_calls       3.60       3.20       3.34       3.32        3.00
            total_call_duration      42.38      37.30      46.87      47.72       55.60
                   pickup_ratio       0.70       0.67       0.69       0.69        0.72
               avg_web_activity      37.14      81.05     122.29     141.04      167.75
==============================================================================================================
09_Source_Comparison
==============================================================================================================
                        Feature  Orange Episode 1  Orange Episode 2  Orange Episode 3  Orange Episode 4  Orange Episode 5+  Purple Episode 1  Purple Episode 2  Purple Episode 3  Purple Episode 4  Purple Episode 5+  WhatsApp Episode 1  WhatsApp Episode 2  WhatsApp Episode 3  WhatsApp Episode 4  WhatsApp Episode 5+
           active_session_count              1.37              1.38              2.35              2.00              13.19              1.34              1.61              1.85              2.04              18.77                1.34                1.72                2.11                2.40                13.33
            amenities_timespent             24.91             51.87              4.23            100.70             284.14             25.22             78.88            226.81            147.13             392.94               21.75               95.04              264.16              281.63               448.65
               avg_web_activity             71.67            141.45            132.81            157.00             165.30             35.39             68.53             85.30            123.01             151.11               37.14               81.05              122.29              141.04               167.75
 days_to_first_whatsapp_inbound              4.81            137.27             90.82             76.08              20.94             12.20            158.75            110.81             91.77              33.94                0.00              157.73              108.32               88.24                40.32
  days_to_last_whatsapp_inbound             13.12            180.21            124.17             92.52              41.32             75.28            200.22            155.86            127.65              66.59                0.00              200.13              151.92              119.26                68.70
did_reach_site_visit_in_episode              0.04              0.04              0.06              0.04               0.02              0.01              0.02              0.03              0.04               0.04                0.01                0.02                0.03                0.04                 0.05
          episode_duration_days              6.33            106.55             62.20             55.00              29.01              4.51            121.81             80.51             77.13              34.78                4.28              124.00               80.10               68.34                35.99
   episode_stage_movement_count              2.78              2.14              2.09              2.08               2.04              2.68              2.06              2.04              2.04               2.02                2.66                2.08                2.05                2.06                 2.04
 episode_whatsapp_inbound_count              4.27              6.07              5.05              6.36               6.94              1.99              2.46              3.04              3.07               4.05                1.25                2.50                3.07                3.10                 3.37
has_whatsapp_inbound_in_episode              0.06              0.51              0.49              0.49               0.47              0.04              0.53              0.48              0.50               0.45                0.08                0.51                0.46                0.47                 0.40
                 home_timespent             62.30             77.11            111.57            215.62            1156.87             33.97             56.93             89.87            198.59            1568.44               34.38               73.36              156.71              194.37              1012.23
         is_brochure_downloaded              0.40              0.51              0.45              0.52               0.60              0.48              0.47              0.59              0.62               0.76                0.46                0.46                0.61                0.61                 0.67
          is_cost_sheet_clicked              0.10              0.16              0.13              0.19               0.14              0.03              0.05              0.08              0.11               0.20                0.04                0.06                0.10                0.10                 0.19
          is_price_sheet_viewed              0.39              0.45              0.48              0.67               0.74              0.23              0.32              0.45              0.61               0.78                0.23                0.34                0.50                0.62                 0.76
         is_reactivated_episode              0.34              0.31              0.41              0.46               0.66              0.23              0.21              0.29              0.41               0.64                0.22                0.22                0.30                0.42                 0.63
      is_resubmitted_in_episode              0.08              0.08              0.10              0.08               0.22              0.03              0.03              0.06              0.07               0.15                0.04                0.03                0.06                0.07                 0.14
     is_site_visit_book_clicked              0.16              0.09              0.00              0.00               0.19              0.12              0.07              0.10              0.06               0.29                0.13                0.08                0.12                0.08                 0.27
            is_whatsapp_clicked              0.16              0.11              0.06              0.19               0.31              0.14              0.12              0.16              0.15               0.35                0.14                0.14                0.16                0.16                 0.33
             location_timespent             23.17            181.32             15.77            172.74             373.39             33.87             77.52            250.74            175.07             514.29               34.48              115.62              161.75              193.08               500.48
                media_timespent            129.33           1173.88            404.88            105.17             937.11            109.48             78.60            266.64           1452.50             939.43              103.00               87.27              621.51              846.36               997.22
                   pickup_ratio              0.65              0.66              0.69              0.64               0.65              0.70              0.67              0.68              0.69               0.72                0.70                0.67                0.69                0.69                 0.72
                 plan_timespent            115.60            132.14            173.24            169.19            1658.24             70.37            153.30            174.02            307.93            2012.53               62.56              164.57              312.70              356.23              1206.58
                price_timespent             93.15            167.80            183.52            170.34            1513.71             66.26            159.98            150.32            201.99            1409.98               69.44              167.41              203.80              183.02               721.62
  resubmission_count_in_episode              1.47              1.18              1.30              2.00               1.29              1.49              1.62              1.90              4.58               1.38                1.49                1.60                1.94                4.22                 1.33
       specifications_timespent             20.29            154.33              5.64             73.12             665.26             94.01            275.13            458.67            174.05             159.15               81.45              342.09              472.99              216.22               218.51
       total_agent_missed_calls              3.43              2.64              2.37              2.64               2.13              3.14              2.41              2.40              2.54               2.00                2.89                2.41                2.40                2.53                 2.06
           total_answered_calls              1.92              1.38              1.35              1.38               1.97              1.35              1.31              1.34              1.45               1.38                1.34                1.30                1.35                1.45                 1.38
          total_attempted_calls              4.46              3.40              3.57              3.59               4.04              3.66              3.20              3.34              3.34               2.98                3.60                3.20                3.34                3.32                 3.00
            total_call_duration             91.44             50.77             61.53             44.58              78.39             43.20             36.92             44.41             47.52              53.85               42.38               37.30               46.87               47.72                55.60

,Feature,Orange Overall Avg,Purple Overall Avg,WhatsApp Overall Avg
0,total_stage_movements,10.55,8.35,8.24
1,is_reactivated_episode,0.35,0.23,0.23
2,total_web_timespent,183.14,101.27,111.07
3,active_session_count,1.81,1.67,1.66
4,home_timespent,95.93,61.08,63.59
5,price_timespent,182.12,205.60,192.16
6,plan_timespent,194.68,158.98,164.82
7,location_timespent,109.08,85.90,89.83
8,amenities_timespent,82.74,120.87,117.20
9,media_timespent,699.25,479.38,444.44
10,specifications_timespent,142.62,177.48,175.46
11,is_site_visit_book_clicked,0.12,0.12,0.13
12,is_whatsapp_clicked,0.16,0.16,0.16
13,is_brochure_downloaded,0.48,0.52,0.50
14,is_price_sheet_viewed,0.49,0.34,0.34
15,is_cost_sheet_clicked,0.13,0.06,0.06
16,total_session_count,1.90,1.80,1.80
17,resubmission_count_in_episode,1.51,1.68,1.65
18,is_resubmitted_in_episode,0.08,0.04,0.04
19,did_reach_site_visit_in_episode,0.04,0.02,0.02
20,episode_stage_movement_count,2.54,2.53,2.53
21,episode_duration_days,12.53,6.68,6.33
22,episode_whatsapp_inbound_count,5.47,2.47,1.92
23,has_whatsapp_inbound_in_episode,0.22,0.15,0.18
24,days_to_first_whatsapp_inbound,94.96,125.64,85.31
25,days_to_last_whatsapp_inbound,135.27,162.46,119.95
26,total_answered_calls,1.86,1.34,1.34
27,total_inbound_calls,1.34,1.31,1.32
28,total_outbound_calls,6.55,5.34,5.39
29,total_agent_missed_calls,3.30,2.77,2.75
30,total_customer_missed_calls,3.88,3.73,3.70
31,total_attempted_calls,4.02,3.60,3.56
32,total_call_duration,75.82,42.37,41.96
33,pickup_ratio,0.66,0.69,0.70
34,avg_web_activity,116.07,62.05,68.07

In [29]:
# 10–12 — reactivation, participation, conditional intensity
show_sheet("10_Reactivation_Comparison", reactivation_comparison)
show_sheet("11_Participation", participation)
show_sheet("12_Conditional_Intensity", conditional_intensity)

==============================================================================================================
10_Reactivation_Comparison
==============================================================================================================
                        Feature  Non-Reactivated Avg  Reactivated Avg  Absolute Change     % Change
          total_stage_movements                 8.35             7.86            -0.49       -5.84%
         is_reactivated_episode                 0.00             1.00             1.00 New Activity
            total_web_timespent                66.04           137.03            70.99      107.50%
           active_session_count                 1.36             1.71             0.35       26.04%
                 home_timespent                41.81            78.59            36.78       87.97%
                price_timespent               101.23           218.04           116.81      115.38%
                 plan_timespent               107.10           227.48           120.38      112.40%
             location_timespent                70.29           101.37            31.09       44.23%
            amenities_timespent                56.79           147.22            90.43      159.24%
                media_timespent                63.08           522.77           459.69      728.69%
       specifications_timespent               226.92           152.62           -74.30      -32.74%
     is_site_visit_book_clicked                 0.11             0.14             0.02       19.98%
            is_whatsapp_clicked                 0.13             0.18             0.05       36.53%
         is_brochure_downloaded                 0.41             0.55             0.14       35.15%
          is_price_sheet_viewed                 0.23             0.40             0.18       76.42%
          is_cost_sheet_clicked                 0.07             0.05            -0.02      -27.60%
            total_session_count                 1.45             1.85             0.40       27.42%
  resubmission_count_in_episode                 1.41             1.90             0.49       34.34%
      is_resubmitted_in_episode                 0.02             0.08             0.06      250.82%
did_reach_site_visit_in_episode                 0.01             0.03             0.02      152.43%
   episode_stage_movement_count                 2.55             2.46            -0.08       -3.24%
          episode_duration_days                 6.29             6.67             0.38        6.05%
 episode_whatsapp_inbound_count                 1.85             2.82             0.96       51.89%
has_whatsapp_inbound_in_episode                 0.19             0.17            -0.02      -10.04%
 days_to_first_whatsapp_inbound               104.61            24.32           -80.29      -76.75%
  days_to_last_whatsapp_inbound               137.21            40.77           -96.44      -70.29%
           total_answered_calls                 1.33             1.34             0.00        0.36%
            total_inbound_calls                 1.30             1.37             0.08        5.83%
           total_outbound_calls                 5.28             5.31             0.03        0.61%
       total_agent_missed_calls                 2.76             2.73            -0.04       -1.28%
    total_customer_missed_calls                 3.66             3.80             0.14        3.85%
          total_attempted_calls                 3.53             3.63             0.10        2.69%
            total_call_duration                40.23            50.57            10.34       25.70%
                   pickup_ratio                 0.69             0.72             0.02        3.17%
               avg_web_activity                44.63            83.32            38.70       86.72%
==============================================================================================================
11_Participation
==============================================================================================================
                        Feature  Non-Reactivated % Active  Reactivated % Active  Difference (pp)
          total_stage_movements                    100.00                100.00             0.00
         is_reactivated_episode                      0.00                100.00           100.00
            total_web_timespent                      1.79                 12.30            10.51
           active_session_count                      1.79                 12.30            10.51
                 home_timespent                      1.24                  9.30             8.05
                price_timespent                      0.37                  4.59             4.21
                 plan_timespent                      0.64                  4.52             3.88
             location_timespent                      0.29                  3.25             2.96
            amenities_timespent                      0.24                  2.55             2.31
                media_timespent                      0.16                  2.37             2.21
       specifications_timespent                      0.11                  1.71             1.60
     is_site_visit_book_clicked                      0.28                  1.96             1.67
            is_whatsapp_clicked                      0.32                  2.54             2.22
         is_brochure_downloaded                      1.00                  7.82             6.82
          is_price_sheet_viewed                      0.57                  5.78             5.21
          is_cost_sheet_clicked                      0.18                  0.77             0.59
            total_session_count                      2.47                 14.29            11.81
  resubmission_count_in_episode                      2.38                  8.35             5.97
      is_resubmitted_in_episode                      2.38                  8.35             5.97
did_reach_site_visit_in_episode                      1.16                  2.93             1.77
   episode_stage_movement_count                    100.00                100.00             0.00
          episode_duration_days                     99.94                100.00             0.06
 episode_whatsapp_inbound_count                     18.87                 16.97            -1.89
has_whatsapp_inbound_in_episode                     18.87                 16.97            -1.89
 days_to_first_whatsapp_inbound                     18.87                 16.97            -1.89
  days_to_last_whatsapp_inbound                     18.87                 16.97            -1.89
           total_answered_calls                     71.77                 65.15            -6.62
            total_inbound_calls                     14.10                 20.36             6.26
           total_outbound_calls                     98.40                 95.75            -2.64
       total_agent_missed_calls                     70.43                 69.13            -1.30
    total_customer_missed_calls                     60.72                 58.72            -2.00
          total_attempted_calls                     95.01                 91.34            -3.67
            total_call_duration                     71.49                 65.06            -6.43
                   pickup_ratio                     71.77                 65.15            -6.62
               avg_web_activity                      1.79                 12.30            10.51
==============================================================================================================
12_Conditional_Intensity
==============================================================================================================
                        Feature          Cohort  Active Episodes   Mean  Median    P75     P90     P95
          total_stage_movements Non-Reactivated            33252   8.35    7.00  12.00   16.00   19.00
          total_stage_movements     Reactivated             9876   7.86    6.00  11.00   15.00   18.00
         is_reactivated_episode Non-Reactivated                0    NaN     NaN    NaN     NaN     NaN
         is_reactivated_episode     Reactivated            10380   1.00    1.00   1.00    1.00    1.00
            total_web_timespent Non-Reactivated              539  66.04   26.16  89.18  206.87  272.77
            total_web_timespent     Reactivated             1054 137.03   57.88 184.27  391.48  557.35
           active_session_count Non-Reactivated              545   1.36    1.00   2.00    2.00    3.00
           active_session_count     Reactivated             1086   1.71    1.00   2.00    3.00    4.00
                 home_timespent Non-Reactivated              378  41.81   20.89  52.85  117.63  170.79
                 home_timespent     Reactivated              806  78.59   37.60 104.34  217.58  310.77
                price_timespent Non-Reactivated              105 101.23   55.35 121.72  267.21  396.53
                price_timespent     Reactivated              391 218.04  119.00 271.38  571.00  868.54
                 plan_timespent Non-Reactivated              194 107.10   44.71 155.35  312.62  431.73
                 plan_timespent     Reactivated              379 227.48   77.53 266.58  644.13 1027.88
             location_timespent Non-Reactivated               84  70.29   25.43  96.25  204.17  294.74
             location_timespent     Reactivated              281 101.37   28.94 112.00  306.23  511.00
            amenities_timespent Non-Reactivated               67  56.79   18.55  54.79  184.68  248.87
            amenities_timespent     Reactivated              220 147.22   38.56 172.56  422.66  715.19
                media_timespent Non-Reactivated               44  63.08   29.13  80.78  175.42  203.22
                media_timespent     Reactivated              208 522.77  125.57 555.47 1862.28 2677.30
       specifications_timespent Non-Reactivated               32 226.92   96.50 259.72  799.16  900.38
       specifications_timespent     Reactivated              148 152.62   58.29 203.04  448.99  613.27
     is_site_visit_book_clicked Non-Reactivated               98   1.00    1.00   1.00    1.00    1.00
     is_site_visit_book_clicked     Reactivated              203   1.00    1.00   1.00    1.00    1.00
            is_whatsapp_clicked Non-Reactivated              112   1.00    1.00   1.00    1.00    1.00
            is_whatsapp_clicked     Reactivated              264   1.00    1.00   1.00    1.00    1.00
         is_brochure_downloaded Non-Reactivated              348   1.00    1.00   1.00    1.00    1.00
         is_brochure_downloaded     Reactivated              812   1.00    1.00   1.00    1.00    1.00
          is_price_sheet_viewed Non-Reactivated              197   1.00    1.00   1.00    1.00    1.00
          is_price_sheet_viewed     Reactivated              600   1.00    1.00   1.00    1.00    1.00
          is_cost_sheet_clicked Non-Reactivated               64   1.00    1.00   1.00    1.00    1.00
          is_cost_sheet_clicked     Reactivated               80   1.00    1.00   1.00    1.00    1.00
            total_session_count Non-Reactivated              739   1.45    1.00   2.00    2.00    3.00
            total_session_count     Reactivated             1260   1.85    1.00   2.00    4.00    5.00
  resubmission_count_in_episode Non-Reactivated              827   1.41    1.00   1.00    2.00    3.00
  resubmission_count_in_episode     Reactivated              867   1.90    1.00   1.00    2.00    5.00
      is_resubmitted_in_episode Non-Reactivated              827   1.00    1.00   1.00    1.00    1.00
      is_resubmitted_in_episode     Reactivated              867   1.00    1.00   1.00    1.00    1.00
did_reach_site_visit_in_episode Non-Reactivated              403   1.00    1.00   1.00    1.00    1.00
did_reach_site_visit_in_episode     Reactivated              304   1.00    1.00   1.00    1.00    1.00
   episode_stage_movement_count Non-Reactivated            34555   2.55    3.00   3.00    3.00    3.00
   episode_stage_movement_count     Reactivated            10275   2.46    2.00   3.00    3.00    3.00
          episode_duration_days Non-Reactivated            29187   6.29    3.69   8.79   16.88   23.73
          episode_duration_days     Reactivated             8852   6.67    3.98   9.04   18.13   25.48
 episode_whatsapp_inbound_count Non-Reactivated             5972   1.85    1.00   2.00    4.00    5.00
 episode_whatsapp_inbound_count     Reactivated             1677   2.82    2.00   4.00    6.00    8.00
has_whatsapp_inbound_in_episode Non-Reactivated             6554   1.00    1.00   1.00    1.00    1.00
has_whatsapp_inbound_in_episode     Reactivated             1762   1.00    1.00   1.00    1.00    1.00
 days_to_first_whatsapp_inbound Non-Reactivated             6377 104.61   48.98 193.25  281.06  363.13
 days_to_first_whatsapp_inbound     Reactivated             1537  24.32    2.99  33.95   85.46  119.37
  days_to_last_whatsapp_inbound Non-Reactivated             6408 137.21   69.87 242.17  357.20  468.67
  days_to_last_whatsapp_inbound     Reactivated             1575  40.77    5.97  56.05  144.38  192.00
           total_answered_calls Non-Reactivated            22325   1.33    1.00   2.00    2.00    3.00
           total_answered_calls     Reactivated             5963   1.34    1.00   2.00    2.00    3.00
            total_inbound_calls Non-Reactivated             4673   1.30    1.00   1.00    2.00    3.00
            total_inbound_calls     Reactivated             1982   1.37    1.00   2.00    2.00    3.00
           total_outbound_calls Non-Reactivated            33079   5.28    4.00   8.00   12.00   14.00
           total_outbound_calls     Reactivated             9702   5.31    4.00   8.00   12.00   14.00
       total_agent_missed_calls Non-Reactivated            23287   2.76    2.00   4.00    6.00    7.00
       total_agent_missed_calls     Reactivated             6839   2.73    2.00   4.00    5.00    6.00
    total_customer_missed_calls Non-Reactivated            20697   3.66    3.00   5.00    7.00    9.00
    total_customer_missed_calls     Reactivated             5970   3.80    3.00   6.00    7.00    9.00
          total_attempted_calls Non-Reactivated            32189   3.53    3.00   5.00    7.00    9.00
          total_attempted_calls     Reactivated             9257   3.63    3.00   5.00    7.00    9.00
            total_call_duration Non-Reactivated            21514  40.23   31.00  50.19   83.00  106.16
            total_call_duration     Reactivated             5785  50.57   33.00  61.87  118.91  160.11
                   pickup_ratio Non-Reactivated            24930   0.69    0.80   1.00    1.00    1.00
                   pickup_ratio     Reactivated             6763   0.72    1.00   1.00    1.00    1.00
               avg_web_activity Non-Reactivated              557  44.63   19.04  62.79  131.25  164.51
               avg_web_activity     Reactivated             1150  83.32   46.33 124.20  214.47  295.17

,Feature,Cohort,Active Episodes,Mean,Median,P75,P90,P95
0,total_stage_movements,Non-Reactivated,33252,8.35,7.00,12.00,16.00,19.00
1,total_stage_movements,Reactivated,9876,7.86,6.00,11.00,15.00,18.00
2,is_reactivated_episode,Non-Reactivated,0,NaN,NaN,NaN,NaN,NaN
3,is_reactivated_episode,Reactivated,10380,1.00,1.00,1.00,1.00,1.00
4,total_web_timespent,Non-Reactivated,539,66.04,26.16,89.18,206.87,272.77
...,...,...,...,...,...,...,...,...
65,total_call_duration,Reactivated,5785,50.57,33.00,61.87,118.91,160.11
66,pickup_ratio,Non-Reactivated,24930,0.69,0.80,1.00,1.00,1.00
67,pickup_ratio,Reactivated,6763,0.72,1.00,1.00,1.00,1.00
68,avg_web_activity,Non-Reactivated,557,44.63,19.04,62.79,131.25,164.51
69,avg_web_activity,Reactivated,1150,83.32,46.33,124.20,214.47,295.17

In [30]:
# 13 — View B within-lead pairs
show_sheet("13_Within_Lead_Pairs", within_lead_pairs, drop_cols=["test_used", "p_value", "% unchanged"])

==============================================================================================================
13_Within_Lead_Pairs
==============================================================================================================
    pair                         feature  active_pair_count  previous_average  current_average  mean_shift   % change  % increased  % decreased significance
  2 -> 1           total_stage_movements               7608              8.36             7.24       -1.12    -13.35%        43.44        48.71       p<0.05
  3 -> 2           total_stage_movements               1676              6.82             7.28        0.46      6.73%        48.21        42.60           NS
  4 -> 3           total_stage_movements                505              7.29             7.44        0.15      2.08%        49.50        41.39       p<0.05
5+ -> 4+           total_stage_movements                591              5.41             6.11        0.71     13.05%        45.18        39.76           NS
  2 -> 1          is_reactivated_episode               7608              1.00             0.22       -0.78    -77.97%         0.00        77.97       p<0.05
  3 -> 2          is_reactivated_episode               1676              1.00             0.30       -0.70    -69.87%         0.00        69.87       p<0.05
  4 -> 3          is_reactivated_episode                505              1.00             0.42       -0.58    -57.62%         0.00        57.62       p<0.05
5+ -> 4+          is_reactivated_episode                591              1.00             0.64       -0.36    -36.21%         0.00        36.21       p<0.05
  2 -> 1             total_web_timespent               7608             60.94           124.45       63.51    104.22%         5.19         8.32           NS
  3 -> 2             total_web_timespent               1676            181.28           401.71      220.44    121.60%         5.67        11.52           NS
  4 -> 3             total_web_timespent                505            678.59           434.04     -244.55    -36.04%        10.30        11.88           NS
5+ -> 4+             total_web_timespent                591           1857.74          3081.09     1223.35     65.85%        20.14        29.10           NS
  2 -> 1            active_session_count               7608              1.36             1.72        0.36     26.69%         5.01         7.77       p<0.05
  3 -> 2            active_session_count               1676              1.74             2.27        0.52     30.10%         5.49        11.10           NS
  4 -> 3            active_session_count                505              3.28             2.39       -0.88    -26.93%         8.51        11.29           NS
5+ -> 4+            active_session_count                591             11.05            14.28        3.24     29.30%        20.47        25.89           NS
  2 -> 1                  home_timespent               7608             38.44            73.97       35.53     92.43%         3.90         6.11           NS
  3 -> 2                  home_timespent               1676            100.81           171.39       70.58     70.01%         4.36         8.77           NS
  4 -> 3                  home_timespent                505            267.77           190.54      -77.23    -28.84%         7.13        10.30           NS
5+ -> 4+                  home_timespent                591            903.69           997.22       93.53     10.35%        17.60        23.86           NS
  2 -> 1                 price_timespent               7608             82.94           166.96       84.02    101.30%         1.95         1.55           NS
  3 -> 2                 price_timespent               1676            193.29           203.80       10.50      5.43%         2.39         5.43           NS
  4 -> 3                 price_timespent                505            309.40           183.02     -126.38    -40.85%         5.74         6.53           NS
5+ -> 4+                 price_timespent                591            655.38           708.87       53.50      8.16%        17.09        22.00           NS
  2 -> 1                  plan_timespent               7608             72.70           168.10       95.40    131.22%         2.17         2.02           NS
  3 -> 2                  plan_timespent               1676            175.67           276.04      100.37     57.14%         2.45         4.30           NS
  4 -> 3                  plan_timespent                505            350.44           356.23        5.79      1.65%         6.34         5.15           NS
5+ -> 4+                  plan_timespent                591            905.64           964.52       58.88      6.50%        17.09        20.30           NS
  2 -> 1              location_timespent               7608             34.41            76.35       41.94    121.88%         0.96         1.77           NS
  3 -> 2              location_timespent               1676            125.89           161.75       35.86     28.48%         1.79         2.51           NS
  4 -> 3              location_timespent                505            191.20           193.08        1.88      0.98%         3.96         4.16           NS
5+ -> 4+              location_timespent                591            332.28           428.74       96.45     29.03%        11.17        14.89           NS
  2 -> 1             amenities_timespent               7608             39.83            98.84       59.01    148.17%         0.87         0.87           NS
  3 -> 2             amenities_timespent               1676             96.47           264.16      167.69    173.82%         1.49         2.39           NS
  4 -> 3             amenities_timespent                505            295.61           281.63      -13.98     -4.73%         3.96         3.17           NS
5+ -> 4+             amenities_timespent                591            414.36           418.52        4.15      1.00%        11.51        15.06           NS
  2 -> 1                 media_timespent               7608            109.98            86.46      -23.52    -21.39%         0.78         0.54           NS
  3 -> 2                 media_timespent               1676             99.35           349.74      250.39    252.03%         2.09         1.79           NS
  4 -> 3                 media_timespent                505           2621.94           797.74    -1824.20    -69.57%         1.58         5.74           NS
5+ -> 4+                 media_timespent                591            927.14           888.01      -39.12     -4.22%        12.86        15.06           NS
  2 -> 1        specifications_timespent               7608             85.39           309.06      223.67    261.94%         0.50         0.26           NS
  3 -> 2        specifications_timespent               1676            247.40           455.29      207.89     84.03%         1.13         1.31           NS
  4 -> 3        specifications_timespent                505            602.74           216.22     -386.52    -64.13%         1.98         3.56           NS
5+ -> 4+        specifications_timespent                591            152.67           147.51       -5.16     -3.38%        11.34        11.84           NS
  2 -> 1      is_site_visit_book_clicked               7608              0.13             0.08       -0.04    -34.79%         0.60         1.42       p<0.05
  3 -> 2      is_site_visit_book_clicked               1676              0.09             0.12        0.03     28.97%         0.66         0.95           NS
  4 -> 3      is_site_visit_book_clicked                505              0.13             0.08       -0.05    -41.67%         0.20         1.39       p<0.05
5+ -> 4+      is_site_visit_book_clicked                591              0.22             0.26        0.04     16.90%         3.55         2.71           NS
  2 -> 1             is_whatsapp_clicked               7608              0.14             0.14       -0.01     -3.78%         0.93         1.50       p<0.05
  3 -> 2             is_whatsapp_clicked               1676              0.18             0.16       -0.02    -12.76%         0.84         2.09       p<0.05
  4 -> 3             is_whatsapp_clicked                505              0.19             0.15       -0.03    -17.65%         0.99         1.98           NS
5+ -> 4+             is_whatsapp_clicked                591              0.30             0.32        0.02      7.47%         5.58         5.58           NS
  2 -> 1          is_brochure_downloaded               7608              0.49             0.47       -0.02     -4.74%         2.59         4.59       p<0.05
  3 -> 2          is_brochure_downloaded               1676              0.54             0.61        0.07     13.39%         2.74         5.25       p<0.05
  4 -> 3          is_brochure_downloaded                505              0.71             0.60       -0.11    -15.64%         3.76         7.33       p<0.05
5+ -> 4+          is_brochure_downloaded                591              0.69             0.69        0.00      0.26%         7.95         9.98           NS
  2 -> 1           is_price_sheet_viewed               7608              0.25             0.34        0.09     37.51%         2.17         2.34           NS
  3 -> 2           is_price_sheet_viewed               1676              0.55             0.50       -0.05     -8.97%         2.27         5.85       p<0.05
  4 -> 3           is_price_sheet_viewed                505              0.53             0.62        0.09     16.67%         4.55         4.55           NS
5+ -> 4+           is_price_sheet_viewed                591              0.76             0.77        0.00      0.41%         8.12        10.32           NS
  2 -> 1           is_cost_sheet_clicked               7608              0.03             0.06        0.03    104.49%         0.41         0.28           NS
  3 -> 2           is_cost_sheet_clicked               1676              0.05             0.10        0.06    127.59%         0.72         0.48           NS
  4 -> 3           is_cost_sheet_clicked                505              0.08             0.10        0.03     33.33%         0.79         0.59           NS
5+ -> 4+           is_cost_sheet_clicked                591              0.14             0.17        0.03     19.09%         2.88         2.20           NS
  2 -> 1             total_session_count               7608              1.44             1.87        0.43     29.49%         6.10         9.38       p<0.05
  3 -> 2             total_session_count               1676              1.94             2.33        0.39     20.06%         6.21        11.81           NS
  4 -> 3             total_session_count                505              3.31             2.57       -0.74    -22.30%         8.71        13.07           NS
5+ -> 4+             total_session_count                591             13.36            15.95        2.59     19.39%        21.32        26.57           NS
  2 -> 1   resubmission_count_in_episode               7608              1.67             1.60       -0.06     -3.80%         3.04         7.32       p<0.05
  3 -> 2   resubmission_count_in_episode               1676              1.41             1.94        0.53     37.63%         5.43         6.74           NS
  4 -> 3   resubmission_count_in_episode                505              1.16             4.22        3.05    262.33%         6.53        11.29           NS
5+ -> 4+   resubmission_count_in_episode                591              1.30             1.35        0.05      4.23%        10.15        11.51           NS
  2 -> 1       is_resubmitted_in_episode               7608              0.08             0.03       -0.04    -56.26%         2.90         7.22       p<0.05
  3 -> 2       is_resubmitted_in_episode               1676              0.08             0.06       -0.02    -20.16%         5.07         6.62           NS
  4 -> 3       is_resubmitted_in_episode                505              0.13             0.07       -0.05    -42.19%         5.74        11.09       p<0.05
5+ -> 4+       is_resubmitted_in_episode                591              0.15             0.14       -0.01     -6.59%         8.29         9.31           NS
  2 -> 1 did_reach_site_visit_in_episode               7608              0.02             0.02       -0.00    -14.84%         1.92         2.27           NS
  3 -> 2 did_reach_site_visit_in_episode               1676              0.04             0.03       -0.00    -11.29%         3.10         3.52           NS
  4 -> 3 did_reach_site_visit_in_episode                505              0.05             0.04       -0.01    -12.00%         3.96         4.55           NS
5+ -> 4+ did_reach_site_visit_in_episode                591              0.06             0.05       -0.01    -11.43%         3.21         3.89           NS
  2 -> 1    episode_stage_movement_count               7608              2.60             2.08       -0.52    -20.03%         5.64        54.90       p<0.05
  3 -> 2    episode_stage_movement_count               1676              2.11             2.05       -0.06     -2.82%         5.73        10.26       p<0.05
  4 -> 3    episode_stage_movement_count                505              2.10             2.06       -0.04     -1.70%         6.34        10.30           NS
5+ -> 4+    episode_stage_movement_count                591              2.08             2.04       -0.04     -1.87%         4.23         7.78           NS
  2 -> 1           episode_duration_days               7608              4.40           123.86      119.46   2714.77%        88.77        11.23       p<0.05
  3 -> 2           episode_duration_days               1676             58.53            79.94       21.41     36.59%        51.79        48.21           NS
  4 -> 3           episode_duration_days                505             46.83            68.20       21.37     45.63%        51.88        48.12           NS
5+ -> 4+           episode_duration_days                591             28.02            35.65        7.63     27.23%        50.93        49.07       p<0.05
  2 -> 1  episode_whatsapp_inbound_count               7608              1.50             2.51        1.01     67.41%        47.45         4.32       p<0.05
  3 -> 2  episode_whatsapp_inbound_count               1676              3.25             3.06       -0.19     -5.72%        31.56        23.15       p<0.05
  4 -> 3  episode_whatsapp_inbound_count                505              3.94             3.10       -0.84    -21.41%        32.28        22.77           NS
5+ -> 4+  episode_whatsapp_inbound_count                591              4.04             3.87       -0.17     -4.19%        27.41        24.53           NS
  2 -> 1 has_whatsapp_inbound_in_episode               7608              0.10             0.51        0.41    409.54%        43.64         2.46       p<0.05
  3 -> 2 has_whatsapp_inbound_in_episode               1676              0.36             0.46        0.10     28.95%        23.81        13.42       p<0.05
  4 -> 3 has_whatsapp_inbound_in_episode                505              0.36             0.47        0.11     30.56%        24.36        13.47       p<0.05
5+ -> 4+ has_whatsapp_inbound_in_episode                591              0.37             0.41        0.05     12.50%        19.80        15.23           NS
  2 -> 1  days_to_first_whatsapp_inbound               7608              0.04           157.69      157.65 379116.96%        50.87         2.83       p<0.05
  3 -> 2  days_to_first_whatsapp_inbound               1676             93.55           108.23       14.68     15.69%        34.90        24.76       p<0.05
  4 -> 3  days_to_first_whatsapp_inbound                505             69.71            88.24       18.53     26.59%        35.64        24.36       p<0.05
5+ -> 4+  days_to_first_whatsapp_inbound                591             24.12            37.79       13.68     56.71%        30.63        25.72       p<0.05
  2 -> 1   days_to_last_whatsapp_inbound               7608              0.17           200.05      199.88 115648.52%        50.81         2.88       p<0.05
  3 -> 2   days_to_last_whatsapp_inbound               1676            125.99           151.77       25.78     20.46%        35.20        24.46       p<0.05
  4 -> 3   days_to_last_whatsapp_inbound                505            109.03           119.26       10.23      9.38%        35.84        24.16       p<0.05
5+ -> 4+   days_to_last_whatsapp_inbound                591             40.09            67.09       27.00     67.35%        29.78        26.57       p<0.05
  2 -> 1            total_answered_calls               7608              1.32             1.30       -0.02     -1.24%        21.69        36.13       p<0.05
  3 -> 2            total_answered_calls               1676              1.40             1.34       -0.05     -3.74%        24.94        32.28       p<0.05
  4 -> 3            total_answered_calls                505              1.39             1.45        0.06      4.41%        26.14        28.12           NS
5+ -> 4+            total_answered_calls                591              1.42             1.37       -0.05     -3.47%        25.04        25.72           NS
  2 -> 1             total_inbound_calls               7608              1.36             1.32       -0.04     -2.71%        16.22        14.58       p<0.05
  3 -> 2             total_inbound_calls               1676              1.38             1.41        0.04      2.63%        16.41        18.62           NS
  4 -> 3             total_inbound_calls                505              1.45             1.44       -0.00     -0.06%        15.05        19.21           NS
5+ -> 4+             total_inbound_calls                591              1.44             1.88        0.43     29.89%        14.72        14.04           NS
  2 -> 1            total_outbound_calls               7608              5.41             4.91       -0.50     -9.16%        45.18        42.93       p<0.05
  3 -> 2            total_outbound_calls               1676              5.05             4.90       -0.15     -2.93%        44.03        43.44           NS
  4 -> 3            total_outbound_calls                505              4.89             5.04        0.14      2.96%        44.16        40.99           NS
5+ -> 4+            total_outbound_calls                591              3.10             3.57        0.47     15.05%        37.73        36.04           NS
  2 -> 1        total_agent_missed_calls               7608              3.11             2.41       -0.70    -22.61%        48.80        33.40       p<0.05
  3 -> 2        total_agent_missed_calls               1676              2.46             2.40       -0.06     -2.49%        40.99        37.95           NS
  4 -> 3        total_agent_missed_calls                505              2.36             2.53        0.17      7.09%        40.59        36.24           NS
5+ -> 4+        total_agent_missed_calls                591              1.97             2.02        0.05      2.56%        33.33        33.84           NS
  2 -> 1     total_customer_missed_calls               7608              3.90             3.26       -0.63    -16.26%        34.94        38.24       p<0.05
  3 -> 2     total_customer_missed_calls               1676              3.48             3.40       -0.08     -2.42%        34.43        34.84           NS
  4 -> 3     total_customer_missed_calls                505              3.41             3.30       -0.11     -3.30%        36.24        31.29       p<0.05
5+ -> 4+     total_customer_missed_calls                591              3.04             2.99       -0.05     -1.54%        27.24        23.69           NS

,pair,feature,active_pair_count,previous_average,current_average,mean_shift,% change,% increased,% decreased,significance
0,2 -> 1,total_stage_movements,7608,8.36,7.24,-1.12,-13.35%,43.44,48.71,p<0.05
1,3 -> 2,total_stage_movements,1676,6.82,7.28,0.46,6.73%,48.21,42.60,NS
2,4 -> 3,total_stage_movements,505,7.29,7.44,0.15,2.08%,49.50,41.39,p<0.05
3,5+ -> 4+,total_stage_movements,591,5.41,6.11,0.71,13.05%,45.18,39.76,NS
4,2 -> 1,is_reactivated_episode,7608,1.00,0.22,-0.78,-77.97%,0.00,77.97,p<0.05
...,...,...,...,...,...,...,...,...,...,...
135,5+ -> 4+,pickup_ratio,591,0.76,0.72,-0.03,-4.15%,24.70,26.40,NS
136,2 -> 1,avg_web_activity,7608,40.19,81.35,41.16,102.41%,5.24,8.27,NS
137,3 -> 2,avg_web_activity,1676,115.32,121.89,6.57,5.70%,5.49,11.69,NS
138,4 -> 3,avg_web_activity,505,135.40,139.96,4.56,3.37%,9.90,12.28,NS
139,5+ -> 4+,avg_web_activity,591,164.98,161.30,-3.68,-2.23%,20.81,28.43,NS

In [32]:
# 14–16 — stage transitions, site visit, executive summary
show_sheet("14_Site_Visit_Analysis", site_visit_analysis)

==============================================================================================================
14_Site_Visit_Analysis
==============================================================================================================
   Episode  Episodes  did_reach_site_visit_in_episode avg  did_reach_site_visit_in_episode % active  is_site_visit_book_clicked avg  is_site_visit_book_clicked % active
 Episode 1     34735                                 0.01                                      1.28                            0.13                                 0.48
 Episode 2      7608                                 0.02                                      2.04                            0.08                                 0.66
 Episode 3      1676                                 0.03                                      3.28                            0.12                                 1.01
 Episode 4       505                                 0.04                                      4.36                            0.08                                 1.19
Episode 5+       591                                 0.05                                      5.25                            0.26                                10.49

,Episode,Episodes,did_reach_site_visit_in_episode avg,did_reach_site_visit_in_episode % active,is_site_visit_book_clicked avg,is_site_visit_book_clicked % active
0,Episode 1,34735,0.01,1.28,0.13,0.48
1,Episode 2,7608,0.02,2.04,0.08,0.66
2,Episode 3,1676,0.03,3.28,0.12,1.01
3,Episode 4,505,0.04,4.36,0.08,1.19
4,Episode 5+,591,0.05,5.25,0.26,10.49